### ISSUE TITLE
As a user, I want to view detailed information for a single Geniza document so that I can learn about that document.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/geniza#110]
## Testing notes
you can visit any document's public page by going to `/documents/pgpid` using the pgpid of that document. alternatively, when in the admin site, you should see a "view on site" button up by the history button which does the same thing.

- [x] Change a document from public to suppressed in the document admin. Go to that document's detail page and ensure that it's no longer visible.
- [x] View a document detail page (in particular, PGPID 1799 has all the fields you'd need), and confirm that the content and order of the content aligns with your expectations for a minimum viable product.
- [x] Check a document with a IIIF-available fragment (for example, PGP 3951) and confirm that the viewer displays the right fragment below the document metadata.

---

**Is your feature request related to a problem? Please describe.**
This is the document detail page. Information displayed here is TBD by the designs tracked on #60.

## dev notes
- [x] create document detail view (use generic detail view class)
- [x] bind urls for corpus views and document detail (suggest `/documents/pgpid/` for now)
- [x] implement `get_absolute_url` on `Document` model
- [x] create simple base template (adapt from other projects if helpful, but let's keep it simple if we can!)
- [x] create document detail template that displays all information included in the designs, with basic iiif viewer; lets use a prototyping library like tachyons or similar for now to keep this simple (no local scss compilation)
- [x] unit test for template logic that checks that information is/isn't displayed, formatting/display agnostic as much as possible
- [x] suppress documents that aren't public by editing the `get_queryset` method
- [ ] add custom management command as described in PR notes
- [ ] hide field names except for SRs

Gissoo's document detail design:
https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza-(Project-team)

**Comment by kmcelwee** [comment]
In order to generate `.po` files, we'll need the top level `geniza/locale` directory even if empty. And you'll need to run `python ../manage.py makemigrations --all` from within `geniza/geniza`. `django-admin` cannot be used because it does not appropriately load our settings file. We run the command from within `geniza/geniza` in order to avoid translating files like `manage.py`.

**Comment by thatbudakguy** [comment]
bumping to 5 for additional template tests, fixtures, and basic template scaffolding

**Comment by richmanrachel** [comment]
Wow! This is so exciting!!! I definitely won't close this until @mrustow sees it, but all of your asks work.

The only problem I have is that we need to define what the information we have is:
![image](https://user-images.githubusercontent.com/68028846/115920236-e6fe7080-a447-11eb-85bb-26afd0867843.png)
- If I were a new user, I might think that this document is dated 1799 (rather than that being the PGP ID), and 1990 would also be very confusing. Let's just include our titles for all of these fields before the information. Ex. "Input into the PGP: 1990"

**Comment by richmanrachel** [comment]
Oh my gosh, playing around with this more, and I love the "View on Site" feature to transition between front and backend!!!

**Comment by gissoo** [comment]
@thatbudakguy thank you for sharing!! 
- For some reason the link to the designs on Figma does not take me to the designs  
Here are the links for mobile and tablet: https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza-Project-team?node-id=572%3A0
Here are the links for desktop: https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza-Project-team?node-id=572%3A2204

- on mobile the description field should be wider – [look here](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza-Project-team?node-id=572%3A26)
- there is a bit of an issue with the image viewer on mobile right now, I'm sure we will fix these. 
- The #CUDL would eventually need be on the right on the page 
- The document date field is missing – I think it would be better to have labels for these (input date: / document date:) to make them more readable otherwise the entire upper part of the page will be full of numbers along with the pgp id and the shelfmark ..
- When I continue with my experiments with the page title and how it would look on the results list I will also experiment with the position of the nav on this page (the nav for document detail, scholarship records, and external links)

**Comment by mrustow** [comment]
- The functionality of "view on site" is fantastic. 
- I agree with Rachel that the fields need to be labeled/defined.
- Seeing this in context, I would much prefer for the header to be the shelfmark(s). It's the way researchers think, and it's ontological, whereas type is more interpretive. 
- Following from there, it might be better for PGPID not to be part of the header, because that would be a lot of numbers. It could be a labeled field below.

**Comment by mrustow** [comment]
btw the Figma diagram for document view seems to have shelfmark as the header. (although there's no PGPID)

**Comment by rlskoeser** [comment]
tagging @gissoo since she's working on options for the page title/header

**Comment by rlskoeser** [comment]
@mrustow @richmanrachel the document title will be revised after Gissoo has a chance to share her options and you all decide, so we'll track that change on a separate issue. I adjusted the page to display a label for input date. Is there anything else you want to see changed at this point before you're ready to sign off?

**Comment by richmanrachel** [comment]
Thank you for moving the "Input Date" label in line with the date itself. Leaving the screenshot here for myself to mark change. Closing now :)

![image](https://user-images.githubusercontent.com/68028846/116889352-73542480-abfa-11eb-8075-41592c363e03.png)
