### ISSUE TITLE
Add Arabic type styles for the site so that users can read and navigate the content in Arabic 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#1135]
@blms we are using Amiri for transcription content, and Hassan for all other site content. [WOFF Hassan files are here](https://drive.google.com/drive/u/0/folders/1efxagFKcC-Rs2clzYFBHa38yVYBdHjnk) and [TTF Amiri files are here](https://drive.google.com/drive/u/0/folders/1AAVmtlnN2zDOJt5JFi55mM_XP2nIf_qG) – I couldn't get the WOFF format of Amiri. 

[Here in Figma you can find all the Arabic type styles ](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=2449%3A63669)

let me know if you have any questions.

**Comment by blms** [comment]
Thanks, @gissoo! This looks very clear. (Is this meant to be my implementation issue, or just for me to review the design?)

@rlskoeser is it OK that the second font is only available in TTF?

If so—we will still need to move Amiri into the "woff files only" folder so that devs know where to download it for their local install. As such, we'll probably need to rename that folder to "font files only" or something along those lines! (And I'll update the dev notes accordingly.)

**Comment by rlskoeser** [comment]
@blms can we / should we generate WOFF from the TTF ourselves? or is TTF fine for web font? agree everything should be in the same folder either way

**Comment by gissoo** [comment]
Just to document some decisions here due to implementation complexities:
for cases where Arabic and Latin are mixed, such as the descriptions, and metadata fields, Ben and I agreed on going with a larger line height (30), and a fixed size gap between the Latin and Arabic of 125% (in most cases Arabic being 25px and Latin 20px)
