### ISSUE TITLE
When adding a new fragment into admin, inputting a non-IIIF URL into the IIIF URL field messes with admin site function.

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1210]
**Describe the bug**
When adding a new Bodleian fragment with an existing image, an RA input the image URL into the IIIF URL field (admin production). Bodleian isn't on IIIF so when the RA tried to save changes and enter the new fragment, the admin site took a long time to update and the connection kept interrupting. When the saved change went through, there were 121 identical related fragments created for the same document. (For reference, it's Bodl. MS Heb. d 74/19). The admin and production site then slowed down and even crashed before Rebecca restarted it.

**Expected behavior**
I want the IIIF URL field to  validate whether the URL entered is a valid IIIF manifest. If it is not valid, I expect an immediate error message to prevent saved changes from going through with the incorrect IIIF URL.

**Comment by blms** [comment]
@kseniaryzhova I wasn't able to replicate this trying a few random URLs. Can you provide the URL that originally caused this error?

Some additional thoughts:
- I can't find a standard URL representation for a IIIF manifest. Examples given in the Presentation API docs are like `https://example.org/iiif/book1/manifest`, which would be hard to match unless we know the pattern ahead of time for each institution. @rlskoeser any thoughts on that?
- The only way I can think to validate an IIIF manifest is by checking its contents, which Djiffy already does.
- I did receive an error when I put in some random URLs, but it was the wrong error. The error was a local manifest caching error instead of a IIIF error. That's because [this code will not run for `IIIFException`](https://github.com/Princeton-CDH/geniza/blob/08aa0e833132e57a97b75f6cd15bd9a5b3ebcbb1/geniza/corpus/models.py#L351-L356), due to [this line in Djiffy](https://github.com/Princeton-CDH/djiffy/blob/f608829a14167df3c417be4a9888c4593d9c0820/djiffy/importer.py#L61). @rlskoeser maybe we need a way of opting out of the `continue` behavior in Djiffy?

**Comment by kseniaryzhova** [comment]
@blms I asked the originator of this issue and he can't find the link. I haven't had this problem in a while. Marking it as a won't solve until there's more information. But take it off your list for now. Either way, not very many people should be messing with importing images into the PGP since we have you and RSK ingest most of the collections that are compatible anyway.

**Comment by rlskoeser** [comment]
I thought I experienced something related to this problem too! But I don't remember exactly. Doesn't sound like it's a high priority.

Since you're marking it as a "won't fix", I'm going to close it. We can always re-open or open a new issue if this something lik this happens again.
