### ISSUE TITLE
Editing/deleting parts of annotation box titles results in unexpected behavior (no change or deleting entire annotation box)

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1221]
### testing notes (QA)

- [x] On the [QA site](https://test-geniza.cdh.princeton.edu/) transcription/translation editor, the below bug should no longer occur.

---

**Describe the bug**
When I go to delete a portion of a title for an existing annotation box, it either does nothing or deletes the entire title and the annotation box. without warning. See video.

**To reproduce**
See video: https://clipchamp.com/watch/cyzDf9MOL0H
Testing in test site, PGPID 733.

**Expected behavior**
When I go to edit a title, I want my edits to be immediately reflected in the transcription editor (so I can choose to save or cancel, etc) and I do not want for the entire annotation box to be affected by an edit of the title.

**Comment by blms** [comment]
@kseniaryzhova Tried following along with the video but I can't replicate this bug, it seems to work fine. Is it possible this was fixed by the most recent changes to the transcription editor?

**Comment by kseniaryzhova** [comment]
@blms still an issue. Will send you a video via chat.

**Comment by blms** [comment]
Small update on this... annotorious-OSD released my patch for this, the `disableDeleteKey`, in version 2.7.11. What I had forgotten entirely was that we were pinned to 2.7.6 because of a bug preventing our annotations from loading introduced in the following version.

I tracked down the bug today and opened a PR with a fix on their repo: https://github.com/annotorious/annotorious-openseadragon/pull/180. Both `disableDeleteKey` and my other bugfix work for me now locally, but it may be some time before we're able to get it into an Annotorious release and subsequently upgrade the dependency in our code.

**Comment by kseniaryzhova** [comment]
@blms no issues, it works! Thank you, closing!
