### ISSUE TITLE
As a content editor, I want the log entry to record and differentiate between users who input someone else's transcription versus users who created a new transcription so I can give the appropriate credit where it's due.

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1260]
## Testing notes

On the [QA site admin](https://test-geniza.cdh.princeton.edu/admin/), go to a document and add a footnote (not a digital edition). Click "save and continue editing." 
- [x] Then, add a transcription using the transcription editor. You can choose any source for this.
- [x] Save the transcription, then make an edit to it, and save it again.

Return to the document in the admin, and click the "History" button. 
- [x] Under "Change history" you should see an entry for the footnote you added manually. 
- [x] Under "Related footnote(s) change history", you should see an entry for the digital edition you just made by transcribing. Clicking on that digital edition should show you the source (including author information) and allow you to add notes.
- [x] Under "Related annotation(s) change history", you should also see history entries for the transcription you made, and the edits you made to it.
- [x] Your user name should be attached to each entry, with a date and timestamp.
- [x] Confirm this makes it clear who added or edited transcriptions, and who is the original author of each (via source on the footnote).

---

**Is your feature request related to a problem? Please describe.**
When a user inputs a transcription, it does not differentiate between users who input their own transcriptions versus users who input others' transcriptions (like from published secondary sources) and those who edited existing transcriptions. This will help us give credit where it's due and also give us a trail to follow if there are issues, questions, etc. 

**Describe the solution you'd like**
I want the log entry in the admin interface to include information about who input a transcription but was not the original author (input), who created the transcription and input it (created by) and who edited an existing transcription (edited). 

**Describe alternatives you've considered**
Original authors of transcriptions who did not input the transcription get credit via their sources so that's solved in a different area of the document detail page in admin.

**Additional context**
By log in the admin interface we mean this. Marina made changes to the transcription yet they were not recorded as such: ![image](https://user-images.githubusercontent.com/105385128/205720488-e1ab3120-1089-4fe2-84c6-805589296d94.png)

**Comment by rlskoeser** [comment]
There are log entries on the annotation objects that track who is creating and updating them and when; for example, here's the annotation for PGPID 25821 https://geniza.princeton.edu/admin/annotations/annotation/996bdaa9-8709-4791-b1c0-2cadb81caec8/history/?_changelist_filters=q%3D25821 

Maybe a simple solution here would be to customize the document history page to show edits on related objects like footnotes and annotations ? (vs. adding extra log entries to documents based on transcription editing)

**Comment by kseniaryzhova** [comment]
@blms This works great! There's a lot of detail here, and I'd like to show it to Marina before approving if that's ok!

**Comment by blms** [comment]
@kseniaryzhova From our meeting, it sounds like the additional feature @mrustow wanted was to be able to see the actual content of a transcription changing between revisions: what those specific changes were, who made them, and on what date.

Those content revisions are not available on the Geniza admin site; rather, they are available on GitHub, in the [pgp-text](https://github.com/princetongenizalab/pgp-text/) repo.

If the following instructions are sufficient, in combination with the admin site feature that Ksenia tested earlier in this issue, then we can consider this as passed testing and can close.

---

Instructions for how to access the revision history of a transcription:
1. Visit the [pgp-text GitHub page](https://github.com/princetongenizalab/pgp-text/).
2. Locate the transcribed document by PGPID; for example, for PGPID 10591, visit the [`10000`](https://github.com/princetongenizalab/pgp-text/tree/main/10000) directory, then click on [`10591`](https://github.com/princetongenizalab/pgp-text/tree/main/10000/10591).
3. Each transcription should have an associated HTML and TXT file in that directory. Click on one of them; the TXT file might be the easiest to read because it is plain text with no markup. For example, here is [the TXT file for a transcription by Marina on PGPID 10591](https://github.com/princetongenizalab/pgp-text/blob/main/10000/10591/PGPID10591_s29_rustow_transcription.txt).
4. In the top right corner, click "History". It should take you to [this History page](https://github.com/princetongenizalab/pgp-text/commits/main/10000/10591/PGPID10591_s29_rustow_transcription.txt).
   ![Screen Shot 2023-01-23 at 3 35 39 PM (2)](https://user-images.githubusercontent.com/7234006/214144555-e9f88702-c83b-44d1-b589-8a675075cd36.png)
5. You should now see a list of all revisions with the date, and the username of each revision's author.
   ![Screen Shot 2023-01-23 at 3 37 51 PM (2)](https://user-images.githubusercontent.com/7234006/214144958-aecd7ea3-7a8d-44e4-9b83-912029991c25.png)
6. To see how the content changed in the revision, click on the bold text that says "Automated data export from PGP - PGPID 10591" (for example) on the date and time of the revision you want to see. This should take you to a page that shows you changes in actual transcription content, with red highlights for deletion, and green highlights for addition. For example, [here is the page for the most recent revision](https://github.com/princetongenizalab/pgp-text/commit/7b0c896d19bde2ccf9ab5985cb7eeb9fe81f8283).
7. (optional) If you would like to view the whole transcription, exactly as it appeared at a certain point in time, you can click the "View at this point in history" on the History page you reached in step 4.
   ![Screen Shot 2023-01-23 at 3 45 27 PM (2)](https://user-images.githubusercontent.com/7234006/214146289-b85075f9-1a2a-4951-8cca-a5598b4cde94.png)

**Comment by blms** [comment]
It is also worth mentioning that the repo I just linked to in the previous comment will only reflect revisions made on the production site.

If you want to test this out on the test site, make some revisions to a transcription, and then visit the [test-pgp-annotations](https://github.com/Princeton-CDH/test-pgp-annotations) page. Follow the same instructions as above, starting from step 2.

I'm not sure how complete the data there is, but it should reflect any transcription revisions made directly on the test site.

Thanks @kseniaryzhova for bringing that to my attention!

**Comment by kseniaryzhova** [comment]
@blms shared with Marina and Rachel - this is an acceptable solution, thank you! Only thing is to discuss who has access (so we can tell any interested parties where to go to see this)

**Comment by rlskoeser** [comment]
fwiw, probably possible to add a link from the public site to the backup / history for that transcription — should be able to generate the links programmatically; would benefit from design input in terms of where to put the link and how to make it intelligible
