### ISSUE TITLE
Replace p. 1 and p. 2 in UPenn image labels with "recto" and "verso" respectively

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1292]
**Is your feature request related to a problem? Please describe.**
UPenn labels their images p. 1 and p. 2 (recto and verso respectively), which is what we display on the PGP. To avoid confusion, we would like to have the images display recto and verso instead of pt. 1 and pt. 2 in order to closely align with how we display other images.

**Describe the solution you'd like**
Find and replace for all UPenn images that have p. 1 and p. 2 in the image labels. The images haven't been ingested yet but I have screens
![image (4)](https://user-images.githubusercontent.com/105385128/211905103-049c5fcc-7189-4fbb-99bc-bbcb7235597a.png)
hot of how it currently displays in QA.

**Comment by blms** [comment]
@kseniaryzhova Since we aren't remixing / hosting this IIIF, we won't be able to actually make manifest changes without a big time investment—and RSK and I agree that it's likely not worth the trouble just for this one labeling change. However, it should be possible to _just_ override the display of the image label as it appears on the site, in the location of your screenshot.

But a couple of questions first:

- How important is the consistency for image labels? I see several other examples from other collections where images are labeled inconsistently:
  - [PGPID 4540](https://test-geniza.cdh.princeton.edu/en/documents/4540/), ENA 4100.9c, labeled "1" and "2" 
  - [PGPID 16475](https://test-geniza.cdh.princeton.edu/en/documents/16475/), T-S AS 150.88, labeled "1r" and "1v"
  - [PGPID 31856](https://test-geniza.cdh.princeton.edu/en/documents/31856/), JRL SERIES C 6 + JRL SERIES C 60, labeled "recto" and "verso"
  - [PGPID 2508](https://test-geniza.cdh.princeton.edu/en/documents/2508/), Bodl. MS heb. a 2/21, also labeled "recto" and "verso" but with no comma after the shelfmark
- What should we do with joins, for example, or if there's "p. 3" and "p. 4"? Should we always assume that odd numbers are "recto" and even numbers are "verso"?

**Comment by kseniaryzhova** [comment]
@blms closing because our need for this does not justify the huge time commitment.
