### ISSUE TITLE
Transcription editor annotation boxes malfunctioning on Mac

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1301]
**Describe the bug**
If more than one annotation box is open in a document (one on recto and one on verso) and both are visible on the screen, a Mac user cannot save either of the annotation boxes. Once one of the boxes is no longer visible, then the visible box saves as it should. This behavior is not reproduced for PC users.

**Expected behavior**
I only want one annotation box to be open at a time, regardless of whether the boxes are on two different images.

**Screenshots**

<img width="1360" alt="image (7)" src="https://user-images.githubusercontent.com/105385128/214864432-567abd03-a892-4ee6-a3cb-15e7a4d66c98.png">
<img width="1380" alt="image (8)" src="https://user-images.githubusercontent.com/105385128/214864468-86ac5cc5-0e01-4b74-a3b6-484fbf961642.png">

**Comment by blms** [comment]
@kseniaryzhova I can't replicate this bug. Is it possible that the test banner was in the way of the save button on the first image? If you click "OK" on the test banner does the bug go away?

If not, can you provide more details about what happens when you try to save on Mac in this circumstance? e.g. does the button get pressed, do you see the "saving..." notification, does the editor close?

And if closing the test banner does resolve this, do we still need to disallow multiple annotation editors being worked on simultaneously? If so, I would label that as an "enhancement" rather than "bug" and estimate it at ~6 hours.

**Comment by kseniaryzhova** [comment]
@blms checked with Marina, it really was the testing box getting in the way - works as it should now. Closing, thank you!
