### ISSUE TITLE
Create and propose sitemap for data on the PGP people

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#1336]
I created four sitemap versions for data on people, [you can view them here on Figma](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=2903%3A61437&t=Uq2SDnb7cpfCDnwT-1)

Note:
- the basis of this sitemap is the original sitemap we created and agreed on previously, which incorporates these new possibilities for the data on people. 
- there are notes next to each proposal on what makes each different from the other. 

The team would like to move forward with v2.

**Comment by gissoo** [comment]
@blms please read the description above, review the proposals and let me know what you think!

**Comment by blms** [comment]
@gissoo These proposals look great! Here are my thoughts:

- **v1 and v2**: Having an entirely separate search for people would be a large development endeavor, so it should be carefully considered if that is the wish. I can provide more details if/as needed. It would be much simpler from a dev perspective to incorporate into the current search.
- **v1 and v2**: On the other hand, a new "Person Details" page would incur some extra dev time, but not nearly as much as search. Dependent on design, but if it's fairly similar to the document details page, I can't imagine it would be a huge time sink.
- **v3 and v4**: These two proposals would be much less dev time than v1 and v2. As for the distinction between v3 and v4, having a separate "Related People" details page from the document details page would be only a bit more work than adding a new section to the existing document details page, dependent of course on the complexity of the designs for each. So design implementation here may vary, but from a backend perspective, the two proposals aren't too different.

One last thing, in case you haven't seen it, here's a [diagram of the proposed structure](https://lucid.app/lucidchart/f1d76271-fa5f-4969-a43e-03ebccbe90ec/edit?viewport_loc=-174%2C37%2C2476%2C1437%2C0_0&invitationId=inv_f55ba4e1-177a-492f-a3c9-1a6c958a7bbb) for how People will be represented in the database. Let me know if you have any questions or trouble reading it!

**Comment by gissoo** [comment]
@blms thank you for the feedback! The team had shared the diagram with me. Thank you! Below are a few questions and points:

- From what I understood the diagram of the proposed structure seems to be flexible. Did you identify any gaps between the diagram and the V1 and V2 sitemaps? I'd love to know 
- From my conversations with the team they strongly prefer V2 – which allows the option for a map (I'm still learning what the map entails). 
- However, the overall reasoning for choosing to go with a separate search for people is researchers' need for a people-centric ux – which impacts the data in the search results (they are different from the data displayed in a document search result). This makes it tricky to incorporate the people search with the document search. It only works if there is a lot of overlap between the filters and the search results, which is what I showed in my V3 and V4 proposals (documents are still very central in those proposals) – And the team wants to access people pages in fewer steps which can't happen in V3 and V4 proposals. 
- I am conducting ux research next week to help me understand the details of the research questions/needs, and the scope a little better. 
- @blms can we start discussing dev time and cost for V2 at our meeting next week? I'd love to get a better idea of feasibility (with respect to the team's other priorities) at this stage so we can scope it more carefully. I'll share my first draft of "wireframes" of V2 with you since it might be more helpful than the sitemap.

**Comment by blms** [comment]
@gissoo 

- Great, glad you'd already seen the diagram! Yes, the proposed structure is definitely flexible, but any changes should be discussed and reflected in the diagram. I saw two things that I don't think are present in my diagram:
  - "Role" isn't a field that exists on a person. There are "types" of relationships between people and other entities, for example `PersonDocumentRelation` has a "type" field which could be things like "mentioned," "author," etc. I figure this makes more sense than assigning a single role to a person across the board, since people often have many roles dependent on context.
  - "Description/transcription excerpts where mentioned"—we hadn't planned to do this on such a granular level, and it would likely be a significant dev effort with NER (named entity recognition). I think the only plan for now is to have documents that are manually associated with people, with "types" like "author" etc. Tagging them within the contexts of descriptions and transcriptions seems out of scope for Performant's work in this round.
- Makes sense they would want the design with the most things (V2), but definitely also worth considering dev time and priorities. I don't think a geographical map view had been discussed previously, for example, so it's not in Performant's contracted work or estimates. But of course we are flexible on all things, it would just mean other priorities being dropped!
- Happy to discuss this further at the meeting. In all likelihood I won't be able to give solid estimates until I see wireframes, but can talk scope and figure out where things fit in the priority list.

**Comment by gissoo** [comment]
@blms thank you for writing! These are helpful!
Sorry for the confusion bu the map isn't a geographical map, it's more like a network map of how people are connected via the documents.

**Comment by gissoo** [comment]
I'll go ahead and close this issue. Once we know more about priorities I'll update the sitemap.
