### ISSUE TITLE
As a content editor, I want a translation module added to the transcription editor so I can add and edit translations to Geniza documents using the same interface as transcriptions.

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1337]
## Testing notes (QA)

On the [QA site](https://test-geniza.cdh.princeton.edu/admin), log in as an admin.

- [x] On the public front end, on document detail pages, there should now be a link to "Add a new translation" above the viewer.
  - [x] You should also see this link in the admin site.
- [x] Clicking this link should open a view with the translation panel expanded and the images visible.
- [x] You should be able to add and edit translation blocks the same way as with transcriptions.
  - [x] Try this on a document that already has a transcription. When editing a translation, you should be able to expand the transcription panel to read it. For now, you won't be able to edit the transcription, but its contents should be accessible from this page.
- [x] Save at least one translation block and return to the document detail page. Refresh the page, and the [translation panel button in the viewer](https://github.com/Princeton-CDH/geniza/assets/7234006/fb4e4bff-14d8-434c-9aed-9222cb4b36b8) should now be clickable. (NOTE: Make sure you dismiss the "test site" banner!)
  - [x] Clicking this button should show the translation panel with your new translation content. The translation's language should be indicated in parentheses in the header above the content, and the text you entered should be visible.

---

**Describe the solution you'd like**
We have (mostly Hebrew and English) translations for many of the documents in the PGP. We would like to display these translations on the site next to the transcription and the images so you can compare all three at once.

**Additional context**
Designs for this translation extension have already been made, and Rebecca has anticipated this extension and prepped the code accordingly.

**Comment by kseniaryzhova** [comment]
@blms works as it should! Thanks so much!

**Comment by blms** [comment]
@mrustow I think we discussed that the default has to be images and translation side by side in the editor, so that you can draw rectangles on the images; otherwise, there is no way to create the translation boxes for writing/editing on the right side! But then you can collapse the image and expand the transcription to view that instead.

**Comment by mrustow** [comment]
Ohhhh right — of course!

On May 24, 2023, at 12:05 PM, Ben Silverman ***@***.***> wrote:



@mrustow<https://github.com/mrustow> I think we discussed that the default has to be images and translation side by side in the editor, so that you can draw rectangles on the images; otherwise, there is no way to create the translation boxes for writing/editing on the right side! But then you can collapse the image and expand the transcription to view that instead.
