### ISSUE TITLE
As a user, I want to view detailed information about all the sources that cite this document so that I can learn the volume and kind of academic engagement with the document

### ISSUE THREAD

**Issue by kmcelwee** [Princeton-CDH/geniza#135]
# testing notes
view [designs on figma](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza-Project-team?node-id=572%3A849)

a good example for testing this design is [PGPID 2537](https://test-geniza.cdh.princeton.edu/documents/2537/scholarship/), which has four different editions listed. it's probably a good idea also to test some documents with footnotes to "special" source types (unpublished, book chapters, dissertations, etc).

- how well does the design/implementation capture the information in the sources?
- is it easy to read & understand what types of sources are being listed?
- does it feel like there's anything missing from this page?

**Comment by richmanrachel** [comment]
I'm sorry, but I don't like the way it looks... it's very confusing that it's in a different order than standard bibliographic material. 

Could you please update to make it look more like a bibliography? Name, Title (and in italics if a book and quotations if an article), page number, then Edition/Translation.

**Comment by richmanrachel** [comment]
I also have no idea what 1905 is referring to in the Gil citation:
![image](https://user-images.githubusercontent.com/68028846/122442857-0065f980-cf6d-11eb-8157-730dcef2e01c.png)

**Comment by mrustow** [comment]
1905 is presumably a typo for 1997?

**Comment by mrustow** [comment]
I agree with Rachel on layout.

**Comment by thatbudakguy** [comment]
flagging for @gissoo since feedback is related to design

**Comment by gissoo** [comment]
@thatbudakguy thank you for tagging!! 
- I think this is missing the date/year, to come after the author.
- We had agreed to replace "edition" with "transcription" which is why I have included "transcription" on the search results and the search filter as well along with "discussion" and "translation". I think transcription makes more sense based on our conversation last time. 
- To RR's comment above, I would add "Discussion" too. 

@mrustow @richmanrachel  – regarding the layout, so I can revise the design so that it's not a list view, but rather a more bibliographic view.

**Comment by rlskoeser** [comment]
@richmanrachel this issue should be closed if the functionality works as expected. It was implemented on the previous designs, which you and Marina did review and sign off on — I suspect that the other display problems you found are due to data errors (most likely scholarship parsing errors); you can confirm by checking if the content on the public view matches the data you can view in the admin interface. 

It's good to get your feedback on the designs, and we'll revisit this — but the revisions will be tracked as a new issue.

**Comment by richmanrachel** [comment]
With the understanding that the functionality works and that the design is being fixed according to #253, I will close this issue now :)
