### ISSUE TITLE
Create a sitemap to incorporate the data on places 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#1352]

**Comment by blms** [comment]
@gissoo (cc @kseniaryzhova) Can you point me towards the decision making process for going with a new search page for Places, rather than a browse view (I thought alphabetical by letter like People)? I had thought we were going with the latter with an option to browse by a map.

I ask because it will take a significant amount of additional backend work to implement a search index for places. If all we are indexing is a name (I remember the decision not to add descriptions), that seems like overkill.

Also, do we need a checkbox like People for "should have a Place page", or will all places get a Place page?

**Comment by gissoo** [comment]
@blms sure, the decision making process came from both the findings from the research I conducted and conversations with Marina, Rachel and Ksenia. [Here is the report from the research](https://docs.google.com/document/d/1NjgX-FAUWNBIXQqJxQIPrCaatYpHFPWuzYWW1x9I5Zk/edit#heading=h.qwqkdjo3m90q), below are a few points that would make the search functionality useful: 

- finding the judeoarabic vs Hebrew names of places as well as different names for a
place – e.g. Alexandria vs. Cairo
- seeing info for Various regions – e.g. maghreb, mashregh, sham
- finding the functions of a place/city – e.g. if they raised animals and what kinds, what plants grew and were used, e.g. indigo, whether there was textile manufacturing
- find out which documents mention a specific city

I think the search would make it easier to find specific places the researchers already have in mind. Without it information can still be accessible through document search, but it's not ideal since we are dedicating a browse section for places. The question is how hard would it be to find a specific region or place on the map without a keyword search? It also depends on the density of the information on the map.

**Comment by gissoo** [comment]
I'll go ahead and close this issue.

**Comment by gissoo** [comment]
I have [updated the sitemap and eliminated the search functionality](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/PGP?type=design&node-id=3045%3A68076&mode=design&t=C6bMYXVVQjID8DQ0-1)
