### ISSUE TITLE
Revise document detail page design based on first-pass implementation

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/geniza#136]
1. <s>tags may have spaces in them</s> addressed by adding an underline
2. there's no obvious title for the page (`<h1>`)
3. the PGPID is not shown (could be related to/part of 2.)

@kmcelwee and I thought that it made sense to make the PGPID part of the title of the page, and have that title always viewable. we created #135 to separate out the footnotes/scholarship records page for each document. if we add a title to the document detail page, we should probably add the same title to the scholarship records page.

**Comment by rlskoeser** [comment]
I suspect we'll need to think more about a meaningful, unique (or uniquish?) title would be for these documents — Gissoo said from her research that PGPID is not meaningful to researchers. I think it should probably be available for reference, but not convinced it needs to be that prominent.

Maybe title could be constructed from document type and shelfmark?

When we're ready, could we deliver the initial implementation for Gissoo to review before we ask for acceptance testing? I think it would be valuable for her as she's thinking about revising the designs. (I'm asking partly because what you guys implemented in terms of labels is different than how I'm interpreting Gissoo's designs, but seeing what you did I see it may be kind of fuzzy.)

@thatbudakguy if some of these labels (shelfmark, document type, etc) aren't displayed visually, do you think they would still be helpful for screenreaders /  accessibility?

**Comment by thatbudakguy** [comment]
maybe this isn't the right orientation, but i think the fact that PGPID isn't meaningful to researchers might not be as much of a barrier as we're making it.

part of the novelty of the PGP is that it considers documents in addition to (or even more than) fragments/shelfmarks as the primary constituent of the geniza. there's no existing convention for durable, unique identifiers for documents _because_ nobody has done anything like the PGP – and yet we know that there are many shifting standards for what constitutes a fragment/shelfmark, and libraries/archives continue to complicate the problem. i think the PGP is already "activist" in the sense that it pushes researchers to consider historical materials in ways they otherwise might not, and coming up with a way to refer to documents (as distinct from physical objects) seems aligned with that to me. maybe a PGPID alone isn't the best way to identify a document, but as far as we know it's the only unique way, so perhaps we can still find a way to work it into the title.

> could we deliver the initial implementation for Gissoo to review before we ask for acceptance testing?

makes sense to me!

> if some of these labels (shelfmark, document type, etc) aren't displayed visually, do you think they would still be helpful for screenreaders / accessibility?

definitely – i think we did something similar for search results on s&co, where the record is a `dl` and many of the `dt`s/labels are visually hidden but accessible to SRs.

**Comment by gissoo** [comment]
@rlskoeser @thatbudakguy @kmcelwee thank you for writing. 
Based on our conversations last week I will draft a list of content and design items that would or would not change specifically for the detail view under its epic. 

- You can find the revised the document detail view regarding your concerns in this chore, [here](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza-Project-team?node-id=822%3A10). 

- @thatbudakguy I have applied auto layout for all the data that comes before the description, if you notice any specific changes with spacing or the placement of the fragment visual it's because of the auto layout – it's supposed to make things more practical 

**If you're more specifically concerned with document title please view issue #155 which is awaiting review.**

**Comment by gissoo** [comment]
Since I have addressed the issues in #155, I'll close this issue as well.
