### ISSUE TITLE
Design an interface with a map for browsing and searching places mentioned in PGP documents 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#1382]
@mrustow @richmanrachel @kseniaryzhova  here are the proposals for the place browse and search interface. 

[This is proposal v2a and v2b.](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?type=design&node-id=3121%3A73083&t=W0K6mZY1WoztWqtJ-1) Below are the key points about these two proposals: 

- Browsing the map is independent from the list – you can interact with the points on the map and navigate to the place detail page through the small pop-up cards but the results on the list view stay the same
- if you input a search term the results would reflect on both the map and the list
- If you select a point on the map nothing happens on the list view, and if you select an item in the list view nothing happens on the map
- The difference between v2a and v2b is the page layout on desktop
- The sorting capabilities would only work on the list view

[Here is proposal v3a.](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?type=design&node-id=3121%3A74186&t=W0K6mZY1WoztWqtJ-1) Below are its key points:
- You can search or browse the map and learn more about the place detail pages through popup cards 
- There are no sorting capabilities 

Please let me know your thoughts  – Once I hear more from John Jameson I'll update you on here

**Comment by richmanrachel** [comment]
Thanks, @gissoo! My initial impression is that I would be hesitant to get rid of all sorting capabilities and therefore I lean towards v2b because I like being able to look at both the list and map without scrolling.

Fyi, the first link you dropped doesn't get you to the right place on Figma (I used the second link and zoomed out to find the designs). Ksenia won't have her computer until June 3rd, so I'll screenshot the photos to her on Slack since Figma is extra challenging to navigate on mobile.

**Comment by gissoo** [comment]
John Jameson also prefers the one with the list, and likes v2b more where the map and the list are side-by-side.

**Comment by richmanrachel** [comment]
@gissoo - showed @mrustow the designs during our meeting today, and here are her comments:
1. Would it be possible to toggle between 2b and 3a? I.e. have all the features and availability of 2b, but be able to make the map more full screen if one is enjoying navigating that way?
2. Can we make it so that selecting an item in list view will highlight the place on a map? (otherwise the list doesn't help build as much context/you lose information)

We'll ask Ben while you're away about one more thing, just noting here so I don't forget: Is this design for Places the MVP or the final iteration? Could we do more dynamic map interactions in order to see change over time, for example?

**Comment by gissoo** [comment]
Update from John Jameson regarding interactivity between the map and the list: 

Normally, when there is a change in the results and it updates, we should announce something about the change to the screen readers. E.g., “three results”. But non-sighted screen reader users can’t use maps, so we may not have to worry about accessibility reqs for the map/list interactions.

**Comment by gissoo** [comment]
@blms @kseniaryzhova [this is where we left the place search/browse](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/PGP?type=design&node-id=3121%3A73265&mode=design&t=C6bMYXVVQjID8DQ0-1). The team and John Jameson both preferred the side-by-side view of the map and the list on desktop. Since the team would like some interactions between the map and the list we may not need the card on the map.

**Comment by gissoo** [comment]
I have updated the sitemap and eliminated search functionality
