### ISSUE TITLE
Design public site search filter so that users can filter by language of translation (Hebrew and English)

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1385]
**Description:**
We want a way for public site users to specifically filter by language of translation. Default is to include both English and Hebrew, but we want people to be able to filter out specific languages for more refined/easily accessible search options.

**Comment by gissoo** [comment]
We discussed and narrowed down to [this approach](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/PGP?type=design&node-id=3409%3A13277&mode=design&t=C6bMYXVVQjID8DQ0-1). However Chelsea will revise it so that "Has Translation" would become "Translation Languages" as a multi-select drop down and will nest "any/all" along with the available languages with checkboxes.
