### ISSUE TITLE
As a front end desktop user, I would like to see a bigger version of the document image in order to read the document (especially when no transcription exists).

### ISSUE THREAD

**Issue by richmanrachel** [Princeton-CDH/geniza#1413]
### Testing notes (QA)

On the [QA public site](https://test-geniza.cdh.princeton.edu/), visit a document with only images.

- [x] After a hard refresh, the document with only images should show a new "expand" icon next to the zoom controls and shelfmark for each image
- [x] Clicking that icon should expand the image to fill nearly the full width of the screen
- [x] The zoom and rotation controls should still work on the expanded image, as should panning and zooming on the image itself when deep zoom is activated
- [x] The "expand" icon should also have been replaced by a "collapse" icon, and clicking that should make the image return to its original size
- [x] These icons should also appear on documents with images AND transcription or translation content, but only when those tabs are collapsed and only the image tab is open
- [x] The same should be true in the QA site admin, after a hard refresh

---

**Is your feature request related to a problem? Please describe.**
When I am trying to skim documents for my research that don't yet have transcriptions, the box that the image is in is too narrow for me to read a whole line at a time. So I struggle with having to keep my place in the document while navigating back and forth dragging my mouse to read the document. 

**Describe the solution you'd like**
An optional or default larger image box so that more of the document is visible in landscape at once.

**Describe alternatives you've considered**
Per our meeting 7/5/2023, we are open to different solutions:
- A "full screen" button like the pin/pop-out we have on the transcription editor that would create a full screen image with an x in the corner to avoid scroll-traps
- A default larger box size for docs with images and no transcription.
- Ability for the user to re-size the image box [though Ben already said this is likely harder]
- Changing the box shape so that it is more like a landscape with a cutoff on the bottom but easier to read across. 

**Additional context**
We're not sure if we'll want a similar full screen feature on the editor or not. Seems less useful, but not absurd to have.

**Comment by blms** [comment]
@richmanrachel One thing I was wondering is whether it may be sufficient to resize the browser window _smaller_ in order to activate the mobile layout. This will give you about 900px width, as opposed to the default 640px of the desktop layout. Not huge, but a little bit extra width to work with. Here is a demonstration:

https://github.com/Princeton-CDH/geniza/assets/7234006/ec51b998-e0e4-4b59-bb16-7b82934ed2b2

In comparison, here is what it might look like if we expand all images to nearly the full width by default. My concern here is the amount of scrolling and lack of an "overview"—it's not really possible to see the full length of the document when this is the case.

https://github.com/Princeton-CDH/geniza/assets/7234006/c6258ce9-9c9c-4543-885e-aec6b3f40105

Of course, that still leaves the option to have this "full screen mode" enabled by clicking a button rather than the default. Maybe that's the best middle ground! But I welcome your thoughts (as well as @gissoo, @kseniaryzhova, @mrustow!).

**Comment by kseniaryzhova** [comment]
@blms I honestly think we should just have the full screen mode enabled by a button without any other solution. Because then that keeps the number of clicks you need to do low, but does give you the option to view it full screen if you need to. Honestly I've just been zooming in on the image in my browser, but I am very much a DIYer.

**Comment by blms** [comment]
@kseniaryzhova That's a great idea to use the browser zoom. I wonder if that would resolve the issue in general. Can you try that and see if it works for your needs, @richmanrachel? Of course, since that's not documented anywhere, users may not know to try it…

**Comment by richmanrachel** [comment]
@blms and @kseniaryzhova  - the browser zoom isn't too bad (though I haven't tested it while trying to do a real transcription yet). I think a full screen mode might still be nice for certain research and teaching purposes, though. I'm happy to do it the way Ksenia recommended.

**Comment by blms** [comment]
Sounds good, let's go with the button click then. Thanks both!

**Comment by kseniaryzhova** [comment]
@blms works as it should, although the person best suited to test is currently on maternity leave! Closing, thank you!
