### ISSUE TITLE
As a content editor, I want a "no language" option when entering source languages (with help text) for unpublished transcriptions because the language will automatically be determined by the document languages already present on the doc detail pages.

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1442]
### testing notes (QA)

On the [QA site admin](https://test-geniza.cdh.princeton.edu/admin), navigate to the Sources section. Add or edit a Source.
- [x] There should now be an "Unspecified (unpublished transcriptions)" option in the Source languages dropdown, as agreed upon in Slack.
- [x] Let me know how I should pass along the below links to sets of sources with possibly wrong languages, once the production release with this Unspecified option is completed. (New cleanup chore issue assigned to Ksenia? How do you all keep track of data cleanup tasks?)

---

**Describe the solution you'd like**
When selecting source languages for unpublished transcriptions, I would like a No Language option coupled with help text that specifies "The No Language option should be selected only in the case of unpublished transcriptions because the language of the transcription is already marked on the document detail page." (or something to that effect)

**Describe alternatives you've considered**
We've considered making language selection optional and not obligatory but we do need those source languages to help track translation languages and to help scholars navigate secondary source languages. We also considered selecting transcription languages just as any other source, but then the bibliographic display is confusing in that it displays the language of transcription in parentheses (MR does not like).

**Comment by blms** [comment]
(Note: Unspecified language option isn't available yet, but posting this here in preparation for that.)

In order to help you all maintain consistency across the DB, I've come up with a handful of lists for data cleanup. We can make a new chore issue if that's helpful. I imagine most of these that are unpublished will need the new "Unspecified" language option, but don't want to assume that and programmatically reassign all of them if that's incorrect for any.

- [Sources with no language selected](https://geniza.princeton.edu/admin/footnotes/source/?all=&languages__isnull=True) (from before the constraint was added; note that all of these happen to be unpublished)
- [Sources marked as Judaeo-Arabic](https://geniza.princeton.edu/admin/footnotes/source/?all=&languages__id__exact=6) (I assume all of these are wrong?)
- [Unpublished sources marked as Hebrew](https://geniza.princeton.edu/admin/footnotes/source/?all=&languages__id__exact=3&source_type__id__exact=3)
- [Unpublished sources marked as Arabic](https://geniza.princeton.edu/admin/footnotes/source/?all=&languages__id__exact=8&source_type__id__exact=3)
- [Unpublished sources marked as Ottoman Turkish](https://geniza.princeton.edu/admin/footnotes/source/?all=&languages__id__exact=9&source_type__id__exact=3)

It's possible there are other examples of non-unpublished editions incorrectly marked as Hebrew (I checked Arabic and didn't see any), so it's probably worth going through ALL the sources marked as being in Hebrew and checking them individually:
- [All sources in Hebrew](https://geniza.princeton.edu/admin/footnotes/source/?all=&languages__id__exact=3)

**Comment by kseniaryzhova** [comment]
@blms creating a chore and tagging me in it would be great (if you also include all these lists as well). I'll go put it on my to do list!

Thank you!
