### ISSUE TITLE
As a content editor, I want to record places-to-places relationship on the place page and on the document detail page, so that I can track ambiguity.

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1453]
### testing notes (QA)

In the [QA site admin](https://test-geniza.cdh.princeton.edu/admin):
- [x] Add or edit a Place record. You should be able to add Related Places with the below relationships, "input manually".
- [x] On the record of a related Place you input manually, the "related places (automatically populated)" should show the relationship you just added

---

**Describe the solution you'd like**
We want a way to track relationships between different places in a way that clarifies any ambiguity. 

The places-to-places list should include:
- Possibly the same as
- Not to be confused with

**Comment by blms** [comment]
@kseniaryzhova Question about this. Could it be possible that you will want to track other kinds of relationships between places, or is this only ever going to be used for ambiguity?

I ask because there are two implementation questions:
1. Does it need to ever have converse relationship types, or will all relationships always be symmetrical? If it's only ever tracking ambiguity then I imagine they will always be symmetrical (since ambiguity isn't directional).
2. Do we need the Places-Places list to be an editable/addable list like in People-People, or are these the only two relationship types we ever want to support?

**Comment by kseniaryzhova** [comment]
@blms 
1. For now we envision all the place-place relationships to be symmetrical.
2. We would like the Places-Places list to be editable.

**Comment by kseniaryzhova** [comment]
@blms works as it should, thank you! Closing!
