### ISSUE TITLE
Full shelfmark search for multiple shelfmarks not working in admin

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1498]
**Describe the bug**
Entering more than one shelfmark into the admin search gives 0 results (even if both shelfmarks are confirmed to be in the database). This means we can't search by shelfmarks to form joins. Inputting the one shelfmark into the other's description will also only pull up one result in the shelfmark search, and not the second shelfmark. 

**To reproduce**
1. Go to [document search in admin](https://geniza.princeton.edu/admin/corpus/document/)
2. Search for any two shelfmarks using AND or OR (ex: T-S 10J16.13 OR T-S 10J16.14)
3. See error.
4. Please note that if you search for any of the shelfmarks alone (T-S 10J16.13 for example) it will pop up correctly.

**Expected behavior**
I should be able to enter more than one shelfmark at a time into the admin document search bar and receive the correct search results.

**Device information**
 Malfunctioning on both PC and Mac devices.

**Comment by blms** [comment]
@kseniaryzhova Testing to figure this out, it seems it may be because the `OR` operator only works between the two words that you place it between. In other words:

```
T-S 10J16.13 OR T-S 10J16.14
```

gets parsed as
```
T-S (10J16.13 OR T-S) 10J16.14
```

and since the default operator is AND when unspecified, that fully evaluates to:
```
T-S AND (10J16.13 OR T-S) AND 10J16.14
= T-S AND (T-S) AND 10J16.14
= T-S AND 10J16.14
```

That's why you're getting unexpected results; all this is really saying is "search for all documents with `T-S` and `10J16.14`".

In that case, the correctly formed query would be:
```
T-S (10J16.13 OR 10J16.14)
```

which [does result](https://geniza.princeton.edu/admin/corpus/document/?q=T-S+%2810J16.13+OR+10J16.14%29) in the two expected results, plus the one that mentions one in the description.

Normally this would be something that should be helped by using shelfmark scoped search, but I'm working on a fix for that now as it's not working properly (#1476).

**Comment by kseniaryzhova** [comment]
@blms Not closing because this solution only works for two T-S shelfmarks, but not if it's shelfmarks from more than one collection. 
<img width="827" alt="image" src="https://github.com/Princeton-CDH/geniza/assets/105385128/853afde0-f6a8-48a8-9e9b-02049ff89043">

**Comment by blms** [comment]
@kseniaryzhova I would write that first query as `(T-S 10J16.13) OR (BL OR 10656.16)`: http://localhost:8000/admin/corpus/document/?q=%28T-S+10J16.13%29+OR+%28BL+OR+10656.16%29

> And if you need both shelfmarks for a join and it's in different collections, then you still can't bring both together to merge them in admin.

Does the above cover that case? Or can you give an example of that?

**Comment by blms** [comment]
@kseniaryzhova I would write that first query as (T-S 10J16.13) OR (BL OR 10656.16): 
https://geniza.princeton.edu/admin/corpus/document/?q=%28T-S+10J16.13%29+OR+%28BL+OR+10656.16%29

And if you need both shelfmarks for a join and it's in different collections, then you still can't bring both together to merge them in admin.

Does the above cover that case? Or can you give an example of that?

**Comment by kseniaryzhova** [comment]
@blms no it does cover it, ok! I'll let Marina know! Closing!
