### ISSUE TITLE
As a content admin, I want an event model that can be linked to multiple people, places, and documents, so that I can recreate a person's timeline and link related data in new ways.

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1512]
### Testing notes (QA - round 2)

In the [QA site admin](https://test-geniza.cdh.princeton.edu/admin):
- [x] It should now be possible to add new events from a Person edit page.

### Testing notes (QA)

Visit the [QA site admin](https://test-geniza.cdh.princeton.edu/admin).
- [x] Edit a document. After a hard refresh you should now see a "related events" section near the bottom of the page, with a + button to add an event.
- [x] Clicking this button should bring up a popup in which you can create an event with a name and description.
- [x] Save the event, then "save and continue editing" the document. That event should now be stored under "related events".
- [x] Visit the Events section of the admin. The event you created should appear.
- [x] Edit the event you created. You should be able to attach people, places, and documents to the event.
- [x] Create a new Event from the Events section of the admin. You should not be able to save it without giving it a related document.
- [x] Create and save one with a related document. Visiting that document edit page should now show the event under "related events".
- [x] Edit a person and/or a place. There should now be a "related events" section on each. You should be able to attach related events from this section; however, you should not be able to add a _new_ event from these pages (i.e. no + button). 

---

**Describe the solution you'd like**
I want an event model that has a many to many relationship with people, places and documents. It will be most prevalent on the people pages as it tracks life events. Events are related to dates on documents but are ultimately a different type of information (and there can be many documents reporting an event, and even the date of the event based on documentary evidence is unclear).

**Comment by blms** [comment]
Handful of questions as I'm working on this:

1. Looking back at the original data model diagram I made, I had planned for a field on Events called `certainty` that would allow either "Documentary" or "Inferred." Have we decided that all Events must be supported by documentary evidence, therefore we don't need that field? Or do we also want to allow inferred events?
   - If so, one possible approach to this (rather than a separate field) is that we just allow it to be attached to 0 documents. In that case it's self-evident that it's inferred rather than documentary.
2. Do we need a `notes` field, or is `description` sufficient since contextual data could go there? Or would it be helpful to have a notes field that only appears in the admin?
3. Do any Event relationships with other items need additional / contextual information? Like does an Event-Document relationship need any kind of `type` or `notes` field? (and Event-Place, Event-Person?) Or is it enough to just have the description and name of the event itself?
4. Do we want to include any kind of guidance or standard for naming events, maybe in help text? I'm thinking in particular about making them findable with autocomplete from within the admin interface. If a bunch of events are named similarly (thinking in particular about things like births and deaths), it might become difficult to find the right one when trying to attach it to a Person, for example.
5. Would an overall typology for Events be something useful to have here? Or do we want to leave it up to the editors what to consider Events and not bother with trying to come up with a definitive list of types of them?

**Comment by blms** [comment]
Answers from 3/21 meeting:

1. No `certainty` field, should always be supported by documentary evidence; information of this type should go in `notes` on Document-Event relationship
2. Yes, but only for relationships not the event itself
3. Yes, `notes` for all
4. Probably, but we don't know until more data entered
5. Probably, but we don't know until more data entered

**Comment by kseniaryzhova** [comment]
@blms everything works as it should, keeping open for now just to let the rest of the team test. I also think not being able to add events from the people pages will be problematic, since part of the way we conceive of events is those milestones in a person's life.

**Comment by blms** [comment]
@kseniaryzhova I must have misunderstood the requirements, I'd thought that was the desired behavior! Let's discuss in this week's meeting.

**Comment by kseniaryzhova** [comment]
@blms Works as it should, thank you, closing!
