### ISSUE TITLE
Polygon annotation box requires hard refresh to start working (does not work immediately)

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1513]
### testing notes (QA)

On the QA site, open or create a transcription or translation. After a hard refresh:
- [x] You should be able to shift-click on the canvas without dragging, and then continue to use the polygon or rectangle tools. (No lines or boxes should be drawn, however, until you drag the cursor while holding down shift and the mouse button.)
- [x] The help text should now clarify that you are not meant to click and release, but hold down the mouse button and drag.

---

**Describe the bug**
When the polygon annotation box icon is selected in the TE, it does not immediately start to draw the lines. You have to do a hard refresh and then it will allow you to draw the polygon.

**To reproduce**
1. Go to the transcription editor of any document.
2. Click "create new transcription (or translation)"
3. Click on polygon annotation icon.
4. Shift and click on the image. 
5. See error.
6. Hard refresh
7. Try steps 3-4 again.

**Expected behavior**
I want to be able to draw a polygon annotation box as soon as the icon is selected, without the need for a refresh.

**Screenshots**
[Marina's screencapture documenting the issue](https://princetongeniza.slack.com/files/U018859MNLD/F06A1CNBZ18/polygon_issue.mov)

**Device information**
 - Happened on both Safari and Chrome (PC).

**Comment by blms** [comment]
I'm not able to replicate this one in Chrome (120.0.6099.109) or Safari (16.6) on Mac (13.5.2) using my touchpad. 

Could it be that you are "shift-clicking" once before "shift-dragging"? It behaves a bit strangely when I do that, though it ultimately does start drawing after a couple tries.

Here's when I try Shift+Click on the canvas first, then Shift+Drag:

https://github.com/Princeton-CDH/geniza/assets/7234006/c306983d-6209-4251-ad77-7005c6ecc6b0

And here's when I just Shift+Drag right away after clicking the icon:

https://github.com/Princeton-CDH/geniza/assets/7234006/d1d14ca6-a7d0-452d-a7d9-da0a88edae1d


(In any case, I'm fairly sure this is an issue in the Annotorious library rather than in Geniza!)

**Comment by kseniaryzhova** [comment]
@blms works well, thank you! Closing!
