### ISSUE TITLE
Cursor suddently jumps around in translation editor

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1515]
**Describe the bug**
When inputting or editing a translation in the editor, the cursor will sometimes jump away from the area/place the user is working on.

**To reproduce**
See video below

**Expected behavior**
I want the cursor to stay in the place that I am working on and only move when I chose to move it.

**Screenshots**
[Marina's screencapture
](https://share.icloud.com/photos/0adEJTGaiUR1bFv4M3mldSHlA)
**Device information**
 - Safari
- Chrome

**Comment by blms** [comment]
I can't replicate, but I also can't access the linked video. Would it be possible to upload the screen capture directly here to Github?

**Comment by mrustow** [comment]
Here's the [screen capture](https://www.dropbox.com/scl/fi/sakyfj8mxv64jxb0z1bio/Cursor-jumping-screen-capture.mov?rlkey=z90kxytgfbcezld8bqum73ne7&dl=0). It's a little difficult to tell since I didn't film my hands, but the cursor jumps twice without my moving the mouse or doing anything. Magic? 😁

**Comment by blms** [comment]
@mrustow Really bizarre! I can't replicate this or #1516, and they look related. Tested on Safari 17.3 (MacOS 13.5.2), on the QA site so as to replicate the network conditions as best as possible without 

Asked this on the other one, but do you have any browser extensions installed in Safari (Safari menu --> Settings --> Extensions)? The only other thing would be to clear your cache in case there is some outdated editor code running.

So sorry this is happening, since it looks like these issues impact work badly. I wonder if anyone else is encountering them? It seems to be only the TineMCE text editor that is bugging out, and not any of our code—which makes this more perplexing.

**Comment by mrustow** [comment]
Honestly I’m happy to ice both these issues until or unless they recur!

**Comment by blms** [comment]
@mrustow Sounds good, let's leave these two in the ice box for a while and if after some time they have not reappeared, we can call it a `wontfix`.
