### ISSUE TITLE
Revise the document title so that it can appear on search and browse results, + the document detail view, scholarship records, external links as the page title 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#155]
I have revised the document title, [here](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza-Project-team?node-id=851%3A6486)
You can find the revised document title in following pages in the link above
- document detail view
- scholarship records 
- external links 
- search results 
- browse results 

There is more: 
- PGP ID is at the bottom of the document detail view, scholarship records, and external links.
- There are design proposals for what the UI looks like when a document has 1 shelfmark, vs when it has more than one shelfmark (along with the states, default and selected) – there is also a proposal with a note (blue sticky note) for documents with more than one shelfmark type/group, please look and let me know if it makes sense, I am proposing it for easier readability. 
– used real data for these designs.

Note:
- Since we have decided on the document type + shelfmark# to be the document title I have eliminated them as separate fields in all the pages. 
- I strongly prefer that we do not make the entire page title bold but make it partially bold. 
- The designs assume that a document has only one document type – I hope that's always true. 
- @thatbudakguy I have applied auto layout for all the data that comes before the description on the document detail view, and the all the search and browse results, you may notice specific changes with spacing or the placement of the fragment visual, or spacing and alignment on the search and browse results it's because of the auto layout – it's supposed to make things more practical.

**Comment by thatbudakguy** [comment]
document titles:
- using bold in a title/heading seems a little strange to me; normally the styling for such headings makes them very prominent already. could we use italics instead, or simply separate the shelfmark using parenthesis, like `Literary (ENA 3338.3)`?
- right now, the document types can be a little grammatically awkward as part of a title (for example, `Legal (ENA 3338.3)` should probably say something like `Legal Document (ENA 3338.3)`. do we need to revise them?
- documents do always have exactly one type, so I think we're good there (and iirc we determined in a meeting that "unknown" is okay). with the current data, if we see a document that has two types, we treat that as a sign that it needs to be demerged into two separate documents, because a second type would by definition mean a new document!

designs for multiple shelfmarks:
- it's easy for me to imagine how to implement these, and i like that they're simple. maybe a good frame of reference is the html5 disclosure widget, [implemented using `<details>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) – it is accessible and doesn't require javascript, which is great. i would probably start with this implementation. in the linked example, the only difference from the design is that the little indicator triangle starts out pointing sideways instead of up/down.
- it does seem like we're giving a lot of prominence to the "main" shelfmark (whichever one is outside the collapsible area). how would we decide which one to use, when there are multiple? maybe this doesn't matter as much as I think; would like to hear from the PGP team.
- we decided on #154 that consecutive shelfmarks use a range indicator, so in the designs the example of `ENA 3338.3, 3338.4` would (i think) become `ENA 3338.3–4`. i don't think this makes a huge difference to the design, just wanted to mention.
- the search result designs don't seem to include cases where there are multiple shelfmarks (or I'm missing it). could we have a convention of including a `+` at the end to indicate there are more (non-consecutive) shelfmarks? so for example a document on `ENA 3338.3,  T-S 24.11` would appear as `ENA 3338.3+`, but `ENA 3338.3, 3338.4` would appear as `ENA 3338.3–4` (not joined to any other shelfmarks).

pgpid:
- putting the pgpid at the bottom of the page doesn't make sense to me; implicitly it's saying that this information is the least important thing on the page and I don't think that's true. is there an issue with displaying it in the main metadata block above the description?
- i don't think the pgpid needs to be on pages other than the detail page. as long as the document title appears at the top of detail view/scholarship records/external links, i think this provides enough context to know the document you're viewing.

**Comment by thatbudakguy** [comment]
i also just noticed that the search results have something called `Converted Date` that I don't see on the document detail page. what is this date? also, do we need to be showing so many dates by default in the search results? it seems like other metadata might be more important.

**Comment by thatbudakguy** [comment]
thinking about this a little more, I wonder if it'd be simpler just to have the full list of shelfmarks be part of the main metadata area, with no interaction needed to see all of them. if we're comfortable choosing a "main" shelfmark that becomes part of the document title, then I don't think there's a big difference between hiding the rest of the shelfmarks in a collapsible area up top vs. putting them with the rest of the metadata, and it might even be better to have them be visible by default.

**Comment by rlskoeser** [comment]
I like the title as combination of document type + shelfmark.

I actually like the partially bold version on the document detail page — headings are often by default, but it doesn't bother me to have part of it not be bold. However, I wonder if the search/browse results should match the formatting? Otherwise there is nothing to distinguish the two parts of the title.  If we need to use punctuation to separate them, I don't like parentheses, but could maybe see using a comma or a slash or something.

I echo Nick's concern that some types would be more readable with "document" (but not all, e.g. letter).

I'm ok with displaying the first shelfmark if there are multiple, but I think there should be an indication if there are more (like the + after the first as Nick suggested), and I think it's better to show them by default vs. forcing a user to click to see them. You have multiple shelfmarks listed with commas separating them, but I think it would be better to stick with standard join notation and use the +.  Your comment in blue says that shelfmark "groups" are separated by paragraph but I don't understand what this means. We don't currently model "groups" of shelfmarks within a document.

I also agree that pgpid should not be buried at the bottom — I think it would make more sense to include in the metadata section. Maybe there could be a "technical metadata" section (doesn't have to be labeled) that would include pgpid and input date, which could be slightly de-emphasized but included at the top.

💡 maybe including pgpid in the metadata could serve multiple purposes, if we label it as permalink (which it is)

Not part of this issue, but I'd be interested to see some version of a "cite this document" and/or "cite this transcription" somewhere on the page. I don't know if they would go at the bottom where you have the PGPID right now.

**Comment by gissoo** [comment]
@richmanrachel @mrustow 
Please ignore all the description and the comments above. 

[Here is a revised version of the document title](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza-Project-team?node-id=851%3A6486) on the document detail view + scholarship records + external links + search and browse results pages (for mobile + tablet + desktop)

- On the detail view, scholarship records, and external links, please take a look at the metadata field at the top left of the page below the document title as well, and let me know your thoughts. Let me know if you would like to hop on Zoom and discuss these decisions as well.

**Comment by richmanrachel** [comment]
@gissoo - We like the header with type + Shelfmark, but the comma is confusing. We propose changing it to a colon and also clarifying the types slightly ("legal" to "legal document"; "state" to "state document"; "literary" to "literary text") to make it super clear to the user.

**Comment by richmanrachel** [comment]
I know we're not quite dealing with this yet, but the field names for dating is a problem, fyi. "Original date" should be the date on the document, not a converted date.

**Comment by richmanrachel** [comment]
@gissoo - overall it looks great! 

Just one question, do we know about what font we'll be using for real?

**Comment by thatbudakguy** [comment]
> clarifying the types slightly ("legal" to "legal document"; "state" to "state document"; "literary" to "literary text") to make it super clear to the user.

I also still think we should do this, fwiw. Although you see the word "document" a lot when searching, I think that redundancy is well enough offset by the clarity of what you're actually looking at, especially for people unfamiliar with the geniza. Also, some types still won't have "document" (e.g. "List or table"), so it won't always be repeated.

**Comment by gissoo** [comment]
> I know we're not quite dealing with this yet, but the field names for dating is a problem, fyi. "Original date" should be the date on the document, not a converted date.

@richmanrachel just fyi, the field labels are what I have highlighted. So the field label for dates will be "document date", and "original date (converted date)" will be both in the same field based on a suggestion NB made – because we're starting to have too many fields on the document detail view.  Does this make sense?

**Comment by gissoo** [comment]
> @gissoo - overall it looks great!
> 
> Just one question, do we know about what font we'll be using for real?

That's coming up! Will be working on that in the next iteration.

**Comment by gissoo** [comment]
> @gissoo - We like the header with type + Shelfmark, but the comma is confusing. We propose changing it to a colon and also clarifying the types slightly ("legal" to "legal document"; "state" to "state document"; "literary" to "literary text") to make it super clear to the user.

@richmanrachel @thatbudakguy 
In the case that we always use "Documents" I still think we should not include it in the title **because** we can solve the issue of clarifying what the user is looking at by choosing a clear name for the section, e.g. "document search" so the user knows what they are searching for. 

However, if we have data that is not considered as "documents" and there is a difference between "document" and a "text", and "table" and "list" then I would be ok with making it as part of the title. But one question: is document conceptually parallel to "text", "table", and "list"? Aren't these all different types of documents (a document type)? If something does not belong to these three types that's the only time it's considered as a document?

I'm asking because we have "document types" and "document dates" but including "text" or "table" or "list" as part of some results implies a lack of consistency conceptually. 

Let me know what you think

**Comment by richmanrachel** [comment]
@gissoo >the field labels are what I have highlighted. So the field label for dates will be "document date", and "original date (converted date)" will be both in the same field based on a suggestion NB made – because we're starting to have too many fields on the document detail view. Does this make sense?
- Oh..... you're saying that it will look like "Document Date: 5th Adar 5446 (March 1023 CE)" ? That works! 

>I'm asking because we have "document types" and "document dates" but including "text" or "table" or "list" as part of some results implies a lack of consistency conceptually.
- I see what you mean. I think @mrustow's concern about having "Legal: Shelfmark" as the title without the full phrase "Legal Document" is that since it's a title, the uniformed user might go, "a legal what?" We consider all of our sources "documents" because of the concept of "documentary sources," but while you don't need to modify the word "letter" or "list" to clarify what it is, "state" and "legal" don't quite carry their own weight without being attached to what they're describing. For example, you can say "She wrote a letter" without further qualification, but "She wrote a legal" doesn't make sense. The letter is still a document, but that's implied in the word.

**Comment by gissoo** [comment]
@richmanrachel I have revised the designs based on your comments, you can see them [on this page](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza-Project-team?node-id=851%3A6486): 

- revised the document title on all the pages 
- listed all possible document titles on a small frame 

(I know the points below are not part of this issue, but it was easier to just do them now)
- included PGP ID field on the search results pages 
- also revised so that transcription is part of the search results as well 

I will close this issue for now.
