### ISSUE TITLE
Incorrect words are highlighted in complete word quotation search (Hebrew script)

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1570]
### testing notes

In the [QA site](https://test-geniza.cdh.princeton.edu/en/documents/):
- [x] The below search `"אלממ"` should highlight as expected in search results, when using double quotes.

---

**Describe the bug**
Quotation search of words I know exist in the corpus brings up inexact matches as well.

**To reproduce**
2. Search for `"אלממ"` in double quotes
3. Look at results 8, 10, 16 (1 and 3 are weird too)

**Expected behavior**
Quotation search in any script should bring up exact matches only.

**Comment by blms** [comment]
This is a challenging solr highlighting issue. We have an exact match (unstemmed) field, and exact searches are matched against that. 

But in the highlighting portion of that query, the highlighter uses edismax to search all query fields:

https://github.com/Princeton-CDH/geniza/blob/782fdd94906c61d6e466c93ae23f94e52212bc65/geniza/corpus/solr_queryset.py#L161-L167

Also, the `content_nostem` field isn't present in the highlighted fields:

https://github.com/Princeton-CDH/geniza/blob/782fdd94906c61d6e466c93ae23f94e52212bc65/geniza/corpus/views.py#L176-L195

Simply adding `content_nostem` with `.highlight()` doesn't do the trick, no matter how I mess with the highlight query formation.

@rlskoeser Any ideas off the top of your head as to how I might approach this? Is there a way we can get the exact match highlighted when partial matches are also present in the result?

**Comment by rlskoeser** [comment]
@blms I suspect that you are not getting highlighting back on `content_nostem` because it's indexed but not stored; I'm looking at the fields in the managed-schema file because I had to refresh my memory on this.  You do have to have an active keyword search on the field as well.  Even if you change that field so solr will store them I'm not sure if that fully solves your problem, because right now you have a single `content_nostem` field - I think you would need to revise copy field behavior and define separate fields (`description_nostem` and `transcription_nostem`); then you have to query across all of them, return highlighting for all of them, and then display in priority order (nostem matches first if there are any, then the other copy of the field).

It does make me feel like we're approaching the problem wrong. It seems to go against how Solr is meant to be used, and it it seems increasingly complicated; although I do remember that it took us a while to arrive at the nostem field as a solution for this problem.  

Because of this complexity there may be some trade-offs with the exact searching and highlighting that will be difficult to solve.

**Comment by blms** [comment]
That's super helpful, thank you @rlskoeser! I'd totally forgotten about the indexed vs stored concept in Solr. Great point also about the two separate fields for exact matches.

> It does make me feel like we're approaching the problem wrong. It seems to go against how Solr is meant to be used, and it it seems increasingly complicated; although I do remember that it took us a while to arrive at the nostem field as a solution for this problem.

I agree with that, and I do think there are going to be additional problems; advanced users are really looking for exactly what was on PGPv3, a search that uses only exact character sequence matching, so anything we try to do with solr to match that is inevitably going to come up short. I do think the exact matching with double quotes, at least, is something that everyday users might expect to work, but some of the more complex use cases of this might not really be feasible with solr. I'll be curious to hear your thoughts on all this in our meeting Thursday!

**Comment by kseniaryzhova** [comment]
@blms works as it should! Also tested a few other words like "אלקמח" (which I know for a fact appear in the corpus)! Closing!
