### ISSUE TITLE
As a public site user, I want a search that strictly matches character sequences in transcriptions, and allows the use of regular expressions, so that I can get results like PGPv3 and make more flexible searches.

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1631]
### testing notes (QA)

[Document search view in QA](https://test-geniza.cdh.princeton.edu/en/documents). Don't need thorough testing here since we've already tested regex search extensively. But at least a few things are new:

- [x] The switcher should correctly switch you between general and regex search
- [x] The info button popup should match designs and the agreed upon language
- [x] The popup should link correctly to the how to search page
- [x] All documents with transcriptions should now be searchable via regex—not just the set of a few thousand to match pgpv3

---

Finally putting this in as an issue to track regex search

**Comment by richmanrachel** [comment]
@blms - from a technical standpoint, this looks good!

I have a few things I want to change in terms of our wording, however. Because I want to markup a screenshot, I'll work on that and share it at the meeting later today.

Also, @kseniaryzhova - we need to add the specific RegEx instructions to our How to Search page.

**Comment by kseniaryzhova** [comment]
@blms Works as it should, thanks! Closing!
