### ISSUE TITLE
As a user, I want to search with multiple tags and choose how they should be combined (ANY/ALL) so that I can drill down or combine search results.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#19]
- [x] add faceting on tags field in the solr queryset
- [x] add tag facets input to to search form; display tag name and count for current search (use checkboxes to allow multiple)
- [x] add any/all configuration option specific to tags (radio boxes; "find documents that match [ALL/ANY] selected tags")
- [x] in the view, filter the search based on the selected tags and specified mode
- [x] when generating the search page with tags selected, make sure the form reflects current status (any/all and any selected tags)

**Comment by gissoo** [comment]
@rebeccakoeser thank you!! the functionality definitely works!!

just some ux comments fwiw:

- if you select two tags and select “ALL of these tags” and don’t get a result then you have to select “reset” to be able to see all the tags again which I think is confusing – it might be worth for @sluescher to know this she can expect it when testing. 

- it’s not helpful that the tags window collapses when the “search” button is selected because it just takes more effort to edit what tags are selected..but in this case the tags window plays a more important role which is that it’s the only place on the page the user can see which tags are selected – since in the results the selected tags aren’t highlighted in some way 

- probably not _super_ relevant to the purpose of this issue: I also think the language "ANY" "All of these" can be more clearer, I need more time on this.

**Comment by rlskoeser** [comment]
@sluescher The basic search now has a "filter by tags" option. It's closed by default, you have to click on it to see the tags. We're showing the top 150 tags ordered by the number of documents with that tag. If you select some tags and hit search, the results should be limited to documents with those tags. The ANY/ALL button below the tags let you control how the tag filtering is applied to your search. 

We're currently not displaying tags that have zero count, and the totals displayed for the tags don't take into account the ANY/ALL setting — they will always display the total assuming an ALL/AND combination with your current search terms and filters.

The tag filtering can be combined with keyword searching. If you enter search terms first, you should see the top tags related to that search.

For sign off on this issue, please confirm that the _functionality_ for the tag filtering works as expected. You are welcome to also comment on the UI/UX — we're planning to have Gissoo do some usability testing on this in tandem with hr testing on the cluster search, but your feedback and questions are always helpful.

**Comment by sluescher** [comment]
Looks good! Is the keyword search still applied to all fields? Tags as well? Just curiosity. Other than that, sign off!

**Comment by rlskoeser** [comment]
@sluescher yes, the keyword search fields haven't changed — so right now you could keyword search on a tag and then also filter on the tags that overlap with that search (which might not be all that useful?).

**Comment by sluescher** [comment]
Well, the searched keyword - different from the tags I choose - might end up also being another tag? So it makes sense to search all fields.
