### ISSUE TITLE
As a content editor, I would like to see line numbers in transcriptions, so I can correlate them line-by-line with images and published transcriptions. 

### ISSUE THREAD

**Issue by mrustow** [Princeton-CDH/geniza#224]
The transcriptions look great! The font is clear and legible, and having transcriptions right there in the record is wonderful. Line numbers would be a time-saver for us. It will probably also reduce the likelihood of mismatched lines and fragments. 
![image](https://user-images.githubusercontent.com/73319225/120491131-fc3fb680-c386-11eb-83ec-2e4eaa275a6a.png)

**Comment by thatbudakguy** [comment]
@gissoo fyi — i think the font getting used here is [Lucida Grande](https://en.wikipedia.org/wiki/Lucida_Grande). because we didn't specify a font for hebrew script on the backend yet, the browser will use the first one that your computer has available that supports hebrew script, which on a Mac appears to be Lucida Grande (it's installed by default on most Macs and was the default MacOS UI font until 2014).

Lucida Grande isn't available on Windows, so the transcriptions will probably look pretty different there. If we did choose to use Lucida Grande somewhere on the frontend, it wouldn't need to be downloaded for mac users, which is a small bonus (but definitely not a big deal). According to that Wikipedia page, many sites still use it as their main UI font, and there are some suggested alternatives for Windows.

**Comment by richmanrachel** [comment]
Putting in the Icebox for now. Only crucial for front end development.

**Comment by richmanrachel** [comment]
(Oops, sorry, wasn't supposed to close and couldn't find IceBox label in GitHub... I'll leave that to @rlskoeser in ZenHub)
