### ISSUE TITLE
omit volume when outputting footnote/source string for unpublished sources (i.e. Goitein "typed texts")

### ISSUE THREAD

**Issue by mrustow** [Princeton-CDH/geniza#252]
## testing notes

Check the public display of editor/source information on a document that has an unpublished source with a volume defined in the database and visible in the admin site – the volume should not be displayed on the public site.

Here's a link to the test site for the example referenced below when this issue was reported: [Letter CUL Or.1080 J86](https://test-geniza.cdh.princeton.edu/en/documents/4016/)

---- 

Check out CUL Or. 1080 J86: back end says "Goitein, typed texts CUL," but front end says "Goitein, typed texts (2019)." 

<img width="405" alt="image" src="https://user-images.githubusercontent.com/73319225/122498624-71cd9880-cfbd-11eb-8bfe-694acd8d68b8.png">
<img width="535" alt="image" src="https://user-images.githubusercontent.com/73319225/122498642-7a25d380-cfbd-11eb-88f8-eddfd4d39a96.png">

While I'm here: can we change the template to "Goitein, typed texts (CUL)" (add parens)? 

## dev notes

- [x] suppress volume for unpublished sources

Other source/footnote formatting is now tracked on #313

**Comment by mrustow** [comment]
the error seems to not to be limited to this one document or run of shelfmarks; I just found it in T-S NS J24.

**Comment by rlskoeser** [comment]
@mrustow I think at least two things are going on here:

1. The current PGP site was still not regularly updating whenever you checked this, so you were seeing out of date information (there were definitely parsing errors; this one at least has been cleaned up in the database).
2. The formatting for sources and footnotes needs to be revised. I think I did this on my own (trying to roughly match the format in the metadata spreadsheet) without input or testing from you or Rachel.

Could you provide the source formatting you'd like to see that will work for all our different sources?  Or suggest something and we can figure out what the variations need to be?  It's a little complicated since we have multiple different types and a lot of the fields are optional.  For example, in the case of Goitein's typed texts we put the shelfmark prefixes into the volume field — I can put it in parentheses, but I'm not sure we want volume in parentheses for all sources. Maybe it would work if we did that for all unpublished sources, since I think none of the others have volumes.

(I think somewhere in asana you shared the format you wanted for articles in relation to the scholarship record cleanup work, but I didn't make a note of it.)

**Comment by mrustow** [comment]
Book: 
Moshe Gil, _Palestine during the First Muslim Period, 634–1099_, in Hebrew (Tel Aviv, 1983), vol. 2, doc. 134

Article:
S. D. Goitein, "New Sources from the Geniza" (Hebrew), Tarbiz 18 (1954): 7–19

Book section:
S. D. Goitein, "New Documents on the Gaonate in Palestine," in _Salo Baron Jubilee Volume on the Occasion of His Seventy-fifth Birthday_, ed. Arthur Hyman (New York, 1975), 2:55–74

Dissertation:
Ṣabīḥ ʿAodeh, "Arabic Letters from the Cairo Geniza," in Hebrew (PhD diss., Tel Aviv University, 1982), doc. 5

**Comment by richmanrachel** [comment]
@rlskoeser - Catching up on things now and just wanted to know where this stands? I like your idea of using parentheses for unpublished volumes.

**Comment by rlskoeser** [comment]
@richmanrachel I haven't had a chance to come back to this one, but when I do I will look at the formats Marina has provided and figure out how to generate them from the existing source data fields we have in the database, and account for optional fields.  I think using parentheses for unpublished volumes will work well.

I also think we should consider this a bug, since it is impacting source editor display on the current PGP site. How urgent is it to get this fixed?

**Comment by richmanrachel** [comment]
I wouldn't call it extremely urgent, but it would be nice to have fixed by the end of July, perhaps? That way we still have our summer RAs onboard to help with the bibliographic cleanup needed before and after this change. Does that seem reasonable, @rlskoeser?

**Comment by rlskoeser** [comment]
fixing this should also resolve #236  

I see in the example citations that the language is listed differently depending on the source type, I wonder if they should be more consistent?

**Comment by mrustow** [comment]
We can do (in Hebrew) for everything per CMS, so: 
Author, _Title of Book_ (in foreign language) (City: Publisher, year).
Author, "Title of Article" (in foreign language) # (year): #–#.

**Comment by mrustow** [comment]
i'm not sure they are! but i love CMS and am happy to revise any standards that aren't in line with it.

**Comment by rlskoeser** [comment]
@mrustow @richmanrachel I have a question about the volume display for unpublished sources: another option would be not to display it at all on the public site, and treat it as an admin only field (which I think it kind of is, since we added for convenience of managing the sources in the admin). Is it meaningful externally in any way?

**Comment by richmanrachel** [comment]
@rlskoeser - I agree that it's an admin tool and doesn't need to be publicly displayed. I'll double check with MR on Wednesday if she doesn't respond here.

**Comment by richmanrachel** [comment]
@rlskoeser - Marina agrees!

**Comment by rlskoeser** [comment]
@richmanrachel great, thank you. I'm going to revise this task to just cover that, and track the work to improve the citation formatting on a different issue.

**Comment by richmanrachel** [comment]
Something's odd about the display right now, but the volume has been omitted:
![image](https://user-images.githubusercontent.com/68028846/142681019-55085bc4-0f98-4cef-8234-fcb785b2fd9e.png)
@rlskoeser Should I close and tag someone else to look into design?

**Comment by rlskoeser** [comment]
@richmanrachel that looks wrong, I don't think it's purely a design problem — let me check

**Comment by rlskoeser** [comment]
@richmanrachel just to confirm, is this the url you're looking at? 
https://test-geniza.cdh.princeton.edu/en/documents/4016/

It looks different for me, which makes me wonder if there's a caching problem with some of the old styles. Would you try a hard refresh ? (see [details on hard refresh](https://fabricdigital.co.nz/blog/how-to-hard-refresh-your-browser-and-clear-cache) if needed, I forget if we've gotten into this yet)

**Comment by richmanrachel** [comment]
@rlskoeser - Yes, that's the correct URL. The record shows up fine on the main page, but all of the scholarship records pages are wonky... I'll try a hard refresh.

**Comment by richmanrachel** [comment]
@rlskoeser - Hard refresh isn't helping. And it's an issue for all the scholarship records, ex:
![image](https://user-images.githubusercontent.com/68028846/142682568-8167892c-d994-4494-adf5-c3b7819be5b5.png)

**Comment by rlskoeser** [comment]
oh! thank you for clarifying: we have a separate issue to revisit the scholarship pages. I didn't know they were quite so wonky, but we needed to revise both the citation format and the design, which has now been finalized — so, you can ignore that for now! For the purposes of this task, checking on the detail page is sufficient (and that's the format in the csv for pgp v3).

**Comment by richmanrachel** [comment]
Okay, great! I can close then :)
