### ISSUE TITLE
As a user, I want to see image thumbnails with search results when available, so that I can quickly see which records have images and what they look like.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#28]
## testing notes

- [x] On the [QA site](https://test-geniza.cdh.princeton.edu/documents/), do some searches and confirm that you can see image thumbnails for each result
  - [x] Check documents with no images, one image, two image, and 3+ images
  - [x] Comment feedback here about the design and implementation

**Comment by richmanrachel** [comment]
@rlskoeser - did we decide that we'll keep this as a priority for the frontend but not the backend? While it would be lovely on the backend, the existing boolean is sufficient to assist the researcher.

**Comment by rlskoeser** [comment]
@richmanrachel yes, this is intended for the frontend search. We don't have that much control or space for that in the backend search.  (I wonder if it would be helpful to add and use tags to help us distinguish frontend features from backend/admin features?)

**Comment by richmanrachel** [comment]
@rlskoeser - Yes, adding tags would be extremely helpful. Thanks!

**Comment by blms** [comment]
@richmanrachel @rlskoeser @mrustow @gissoo 

Working on implementing this, and due to the different dimensions of images there are some edge cases that we have to account for. Here's a bunch of examples the current implementation I've come up with so far. Are they acceptable? Is it clear when there are one, two, or more images? Is the sizing appropriate? Looking for any/all feedback!

<details>
<summary>A bunch of example screenshots</summary>

<img width="956" alt="Screen Shot 2022-02-09 at 11 17 32 AM" src="https://user-images.githubusercontent.com/7234006/153243509-4b9e70a4-d1f7-4fe8-91ec-5a4a41bfdcdf.png">
<img width="915" alt="Screen Shot 2022-02-09 at 11 18 11 AM" src="https://user-images.githubusercontent.com/7234006/153243513-efedaf4a-6981-4d98-b1db-66f772515f5f.png">
<img width="930" alt="Screen Shot 2022-02-09 at 11 16 17 AM" src="https://user-images.githubusercontent.com/7234006/153243520-2a3c0c14-25c4-456b-8f21-e9601677e4db.png">
<img width="953" alt="Screen Shot 2022-02-09 at 11 16 26 AM" src="https://user-images.githubusercontent.com/7234006/153243524-6160ab06-aedc-45b0-bee7-7187fedf8a05.png">
<img width="929" alt="Screen Shot 2022-02-09 at 11 16 34 AM" src="https://user-images.githubusercontent.com/7234006/153243527-7dd38f7c-a2fc-4b9f-93c1-859a3d9370a0.png">
<img width="956" alt="Screen Shot 2022-02-09 at 11 16 55 AM" src="https://user-images.githubusercontent.com/7234006/153243531-be3cc969-1fb5-4b75-9090-6a4e41d98ff4.png">
<img width="940" alt="Screen Shot 2022-02-09 at 11 17 04 AM" src="https://user-images.githubusercontent.com/7234006/153243539-03b5fe75-af27-468a-bae5-801f92ebe606.png">
<img width="959" alt="Screen Shot 2022-02-09 at 11 23 52 AM" src="https://user-images.githubusercontent.com/7234006/153244061-7f7dc2dc-f8c4-483e-98a9-ec941c8fa8e2.png">
<img width="927" alt="Screen Shot 2022-02-09 at 11 22 06 AM" src="https://user-images.githubusercontent.com/7234006/153244080-f11c7f95-4cd0-41ab-996a-bcf31e0e926b.png">


</details>

**Comment by richmanrachel** [comment]
@blms - I love it! I think it's very clear

**Comment by rlskoeser** [comment]
@richmanrachel @mrustow do you need/want to see the full image in every case on the search results page? The long, thin image (Ben's second example) really sticks out, it would be nice if we could make the display more consistent with the other images, and shorten it in some way. Should we constrain the height and let it be thinner? Can we limit how much we show, so you only see the top of the image?

**Comment by richmanrachel** [comment]
@rlskoeser - It would be better to see the whole document re-sized rather than cutting it off. Even if it looks really small, this would be more helpful because then we know as researchers how complete the fragment is. Can we maybe see a test comparing long images at same scale to re-sized ones?

**Comment by rlskoeser** [comment]
@richmanrachel thanks, that's good to know — we thought that might be the case. 

@blms could you do a quick test implementation (local browser override would be fine!) limiting the height, so we can see what it looks like?

**Comment by blms** [comment]
@richmanrachel @rlskoeser 

Sure! Here's some examples of what that would look like:

<details>
<summary>constrained height</summary>

<img width="896" alt="Screen Shot 2022-02-09 at 2 29 44 PM" src="https://user-images.githubusercontent.com/7234006/153276148-df1b6b28-0987-4552-99a7-40e3c07f19b5.png">
<img width="916" alt="Screen Shot 2022-02-09 at 2 28 32 PM" src="https://user-images.githubusercontent.com/7234006/153276149-54d20499-7156-4619-98d8-8079546444a7.png">
<img width="902" alt="Screen Shot 2022-02-09 at 2 29 39 PM" src="https://user-images.githubusercontent.com/7234006/153276152-9bcf2345-ed07-4546-a0ac-7ebcf06fe6a4.png">
<img width="889" alt="Screen Shot 2022-02-09 at 2 29 32 PM" src="https://user-images.githubusercontent.com/7234006/153276154-41bf2a1c-85c5-440f-bf34-330e1292040b.png">
<img width="905" alt="Screen Shot 2022-02-09 at 2 28 42 PM" src="https://user-images.githubusercontent.com/7234006/153276145-d0c51bbf-e419-4750-85bc-65f86bacec9e.png">
<img width="932" alt="Screen Shot 2022-02-09 at 2 30 24 PM" src="https://user-images.githubusercontent.com/7234006/153276141-c5993eb9-ba9f-415d-8208-59e8c89fd8ce.png">
</details>

**Comment by rlskoeser** [comment]
Thank you @blms ! that's helpful — I think that works, and is preferable to the excessively long images. What do you think @richmanrachel ?

**Comment by richmanrachel** [comment]
It's hard to tell before getting on the test site, but the constrained does seem to look good! Thanks @blms and @rlskoeser!

**Comment by richmanrachel** [comment]
We love it! Closing!
