### ISSUE TITLE
As a content editor, I want to add data to the database in multiple languages so that I can fully represent existing project data.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#36]
# testing notes
**note** - this issue is a companion to #35, but they address different issues and function differently. this issue covers all the actual PGP data that can be stored in multiple languages, rather than text on the site.
## as a user
see "as a user" on #35; since this part works exactly the same way. then, pick a person from [the list of people](https://test-geniza.cdh.princeton.edu/en/people/). you'll see a basic testing page that tells you what profession that person had. currently, nobody has any profession. let's add one.
## as a content editor
1. go to the [admin backend for the site](https://test-geniza.cdh.princeton.edu/admin/) and click "people". click a person's name to edit them.
2. you'll now see the fields that are available on a person: their name, and their profession. go ahead and pick any profession from the list and save the model.
3. note also that there are three tabs here, labeled according to the language codes of the languages that you can currently browse the test site in. if you go to one of those tabs, the field will be empty, indicating there's no value in that language. we can control which languages are available at the level of each field, but the default is to allow every language that you can browse the site in.
4. go ahead and add a (fake or real) version of the person's name in another language and save the model.
5. if you go back to the public site and visit the page of the person you edited, you'll see a message like "X was a Y", where X is the person's name and Y is the profession you chose. if you switch language, both X and Y should now display in the translated versions you entered! if you didn't enter a translation for the language you chose, it will just display in english instead. note that the _middle_ part of this text ("was a") isn't actually "PGP data", and thus it would be translated via the methods covered in #35.

leave comments/opinions below on how this process went for you.

# dev notes
- [x] model editable in django admin with translation
- [x] simple list page
- [x] simple detail page

**Comment by rlskoeser** [comment]
@thatbudakguy I think this was the library I was thinking of (but I don't know the maintenance status or versions of django it supports): https://django-modeltranslation.readthedocs.io/en/latest/

**Comment by thatbudakguy** [comment]
some notes on how this is working:
- when you access an attribute of a model instance using its regular field name (`profession.title`), you get the value for the localized version of the field that matches Django's currently active language. This means that in templates and views, you usually just use the regular field name and let the language detection middleware do the rest (see #35).
- after you define the fields you want translated in an app's `translations.py`, you need to `makemigrations` so that a new migration can be generated to add the localized versions of the fields. if you change the available languages or default language in `settings.py` (uncommon), you also need to do this.
- there is a setting `MODELTRANSLATION_AUTO_POPULATE` that causes all of the localized versions of a field to be auto-filled with whatever value you supply in the `create()` call (or when loading a fixture, etc). however, I don't think we want to do this, because by default `MODELTRANSLATION_FALLBACK_LANGUAGES` points at the default language, so any time an empty language-specific version of a field is accessed, it'll just return the `en` value, which we make required in `translations.py`, e.g.:
```py
@register(Profession)
class ProfessionTranslationOptions(TranslationOptions):
    fields = ("title",)
    required_languages = ("en",)
```
- so, accessing `some_profession.title_ar` would return the (English) value of `some_profession.title_en` if there's no arabic version of the profession title stored, which is what we want. we leave the non-english versions of localized properties empty until they're filled by a team member, and we don't require them.
- making admin classes inherit from `TabbedTranslationAdmin` adds a nice jQuery-powered tabbed UI to model forms in the admin, so that you can switch between the different-language versions. it loads a little weirdly on my machine, but i think it's preferable to just having the fields all listed out.

**Comment by sluescher** [comment]
We are unable to test because when we reach the admin backend it asks us for login, which works, but does not take us to the backend. 
![Screen Shot 2021-02-11 at 8 32 54 AM](https://user-images.githubusercontent.com/30683720/107648888-dad98400-6c4a-11eb-9fa6-ac658f3f4e7d.png)

**Comment by mrustow** [comment]
Once RSK gave me access, it worked!
