### ISSUE TITLE
As a front end user, I want a transcription and image display that works on mobile devices, and allows me to zoom in and out on images.

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#401]
## testing notes (QA)

Check transcription and image display/interactions for the following kinds of documents, on the document detail page, and confirm that all are working as expected:
- [x] Image(s) and transcription
- [x] Only image(s)
- [x] Only transcription

---

Issue for Mirador edits, as well as implementation of Mirador replacement.

**Comment by rlskoeser** [comment]
@blms I think this may already be done (unless we want to add script indexing & classes to improve transcription display) — however, would appreciate if you could adjust the transcription font display when it is rendered in mirador.

I thought maybe it was too large; Gissoo responded as follows:
> don’t think the issue is the size – I think it’s the spacing between each line # – maybe increase that by 2-4px?
if not, please decrease the type size to 18px on desktop and 16px on mobile only for the mirador view

Also, we need to adjust the `dir: rtl` so it doesn't apply to the section headings that are rendered in the full version of the transcriptions we use in mirador (labels like recto, verso, angled text in margin).

**Comment by blms** [comment]
@rlskoeser @gissoo  Is this more or less what you guys were thinking?

<details>
<summary>Original</summary>

<img width="525" alt="Screen Shot 2022-01-18 at 10 55 03 AM" src="https://user-images.githubusercontent.com/7234006/149972104-d9676b3b-39f9-40af-be92-9c867b6be413.png">
</details>


<details>
<summary>New</summary>

<img width="527" alt="Screen Shot 2022-01-18 at 10 53 01 AM" src="https://user-images.githubusercontent.com/7234006/149971549-c77d5a95-ef3c-4f19-b2dd-fce408385561.png">

</details>

Couple of additional questions on this:

1. Is mobile view for Mirador in MVP (and is it meant to be supported out of the box)? The annotation view is pretty much unusable on mobile right now 😬 Not sure if that's because of the way we're using it, or just how Mirador works with annotations.
2. Are recto and verso transcriptions meant to be annotations on their appropriate page image? I noticed that sometimes (maybe always?) the annotation just appears on the first page in the set, and therefore contains both recto and verso. And then, when you for example change the active image from recto to verso, the transcription disappears altogether. Example: https://test-geniza.cdh.princeton.edu/en/documents/1809/

**Comment by rlskoeser** [comment]
@blms thanks for flagging this — I've been kind of underwhelmed by mirador, it seems pretty clunky even on desktop. I don't know if mirador has mobile support or not — I don't see anything obvious about it in their documentation, but I could ask in the IIIF slack about it.

We don't yet have data about which part of the transcription belongs to which image, and that isn't MVP; right now the transcription text is only attached as an annotation on the first image. I looked briefly into attaching it to every image, but it was challenging because the ids in the annotation and manifest have to match.

Given the problems with mirador (both in general and specifically with mobile), and also the issue with easy access to the transcription text, I wonder if there's a way to do something simpler for the MVP release that is closer to Gissoo's wireframes?

**Comment by rlskoeser** [comment]
forgot to say, but the font looks better in the viewer

**Comment by blms** [comment]
Proposed redesign:

![download-1](https://user-images.githubusercontent.com/7234006/151813015-f65c8fe2-0fef-4e82-b1cd-565df94775c3.png)

**Comment by rlskoeser** [comment]
@richmanrachel @mrustow thanks for your feedback in Slack about this approach. So we have it documented, would one of you please confirm on this issue that you're happy with this approach and not using mirador for the MVP, as long as you're able to see high quality versions of the images?

**Comment by richmanrachel** [comment]
Success! Closing :D
