### ISSUE TITLE
As a user, I want to see existing TEI transcriptions displayed with IIIF images so I can see how using annotations for transcription might work.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#43]
## testing notes

Go to the test site at https://test-geniza.cdh.princeton.edu/iiif/  — you should see the Mirador 3 IIIF viewer with a list of manuscripts to select (note that it does load quite slowly because there are so many manifests in the list). 

When you choose a document to view, it should open with the annotations panel displayed and should show a transcription beside an image. When you close the document you're looking at, use the "start here" at the top right to go back to the list and open another.

The documents available for testing right now are only those that we currently have both IIIF and transcriptions for. For now, I'm attaching all annotations to the first image in the IIIF manifest and setting the annotation zone to be the entire canvas. I'm creating separate annotations for each block of text within a TEI document, as indicated by a label preceding a new section.

I'm setting language direction as rtl and left-aligning everything; I also put all transcription lines into an ordered list, but I haven't yet looked into correcting the TEI documents with un-numbered lines that wrap, so I expect there are cases where the numbers will be wrong. There is no language detection yet.

For sign off on this story, please confirm:
- transcriptions are associated with the correct documents (the association is based on PGP ID in the TEI and IIIF manifest in the metadata spreadsheet)
- distinct blocks of text within a single TEI are correctly grouped

Feel free to add comments with things you notice that are missing and should be addressed when we start refining this. Here are a few things I've noticed so far:
- Transcriptions should sometimes be associated with the second image in a manifest, but I'm not sure how to determine where they belong. It looks like if there is a "recto" or "verso" label, any sections after it are on that side.
- Transcriptions of marginal text often seem to use / to indicate line breaks

----

First pass conversion of TEI transcriptions to IIIF annotation (only for subset of documents with IIIF and transcriptions, for now)

**Comment by rlskoeser** [comment]
If you go to the test site at https://test-geniza.cdh.princeton.edu/iiif/ you should see the Mirador 3 IIIF viewer with a list of manuscripts to select. When you choose one, it should open with the annotations panel displayed and should show a transcription beside an image. When you close the document you're looking at, use the "start here" at the top right to go back to the list and open another.

The documents available for testing right now are only those that we currently have both IIIF and transcriptions for. For now, I'm attaching all annotations to the first image in the IIIF manifest and setting the annotation zone to be the entire canvas.  I'm creating separate annotations for each block of text within a TEI document, as indicated by a label preceding a new section.

I'm setting language direction as rtl and left-aligning everything; I also put all transcription lines into an ordered list, but I haven't yet looked into correcting the TEI documents with un-numbered lines that wrap, so I expect there are cases where the numbers will be wrong. There is no language detection yet.

Things that would be helpful to confirm:
- transcriptions are associated with the correct documents (the association is based on PGP ID in the TEI and IIIF manifest in the metadata spreadsheet)
- distinct blocks of text within a single TEI are correctly grouped

It would also be helpful to get feedback on the things that are missing and should be addressed in refining this. Here are a few things I've noticed so far:
- Transcriptions should sometimes be associated with the second image in a manifest, but I'm not sure how to determine where they belong. It looks like if there is a "recto" or "verso" label, any sections after it are on that side. 
- Transcriptions of marginal text often seem to use / to indicate line breaks

**Comment by mrustow** [comment]
- transcriptions are associated with the correct documents — confirmed
- distinct blocks of text within a single TEI are correctly grouped — **no** e.g., T-S 8J17.16 "page b" should be 2 distinct text blocks (4 lines of text and 3 of address), but are grouped together with consecutive numbers. In the original [TEI](https://geniza.princeton.edu/pgpsearch/?a=object&id=1982) the address didn't have line numbers, so this was numbered automatically?
- Transcriptions should sometimes be associated with the second image in a manifest — confirmed. 
- --> Example: T-S Misc. 24.39 is a bifolio (pamphlet format) with complex ordering; what shows as recto is pages 2-3 of the pamphlet
- --> **Possible solutions** either manually coordinate CUDL recto/verso with PGP recto/verso; or leverage progress on parallel HTR project to coordinate image and text automatically
- Transcriptions of marginal text often seem to use / to indicate line breaks: confirmed. Helpful to leave it there because it indicates that it's marginal?

**Other things we noticed**
- doesn't seem to work on Safari
- images are loading slowly, perhaps due to VPN speed
- Under the "i" for information, we see the CUDL description but not the PGP description; would be ideal to have the option of seeing both or either, clearly labeled as such. (Extra bonus: pingback option where our record can be visible through the Cambridge portal if they so choose?)
- images in the list view are teeny. we were hunting for a letter with angle parking but had to hit-or-miss it. Possible to make the thumbnails bigger, or bigger while hovering? 
- generally in IIIF there doesn't seem to be an option to rotate the page. (Codex bias!) Many of our docs have text that is 180 or 45 degrees off. Full variety of rotation angles (359 of them) would be ideal.

**Comment by rlskoeser** [comment]
Thank you for the detailed feedback and careful testing! Super helpful. I think since this was an experimental implementation it isn't worth revisiting and retesting at this point — it's served the purpose of answering a lot of questions (and raising others!) about converting the TEI transcriptions into IIIF annotations for display with the images.

> distinct blocks of text within a single TEI are correctly grouped — no e.g., T-S 8J17.16 "page b" should be 2 distinct text blocks (4 lines of text and 3 of address), but are grouped together with consecutive numbers. In the original TEI the address didn't have line numbers, so this was numbered automatically?

Thank you for identifying a specific case so I could investigate. I see in the TEI that there are two blank lines — does that indicate the lines that follow should be considered a separate block of text?

I am indeed numbering lines automatically; this was been one of the questions that I didn't get a clear answer on yet, whether we need to preserve the numbers in the tei or if it's ok to autogenerate them. Maybe they do need to be stored so we can ensure they match printed editions.

Thanks for the feedback on the display and interface! I'm going to tag @gissoo to make sure she sees them, although I know some of them (like image rotation) are already included in her plans.

I think it's ok if we close this issue now. We can refer back to the notes here whenever we circle back to working with the transcription data. Any concerns or interest in further follow up at this point @mrustow @sluescher ?

**Comment by sluescher** [comment]
It is hereby closed!
