### ISSUE TITLE
Create a sitemap of the search, holistic search, and doc detail page to communicate the site structure and how the pieces are connected 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#45]
[Here is a link to the sitemap](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza?node-id=75%3A0) (note: just the holistic search and the doc detail page are there now)

**Comment by rlskoeser** [comment]
Note from @gissoo in Slack 11/25:
> I have added the doc detail to the site architecture https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza?node-id=75%3A0

- "Document List" seems vague to me, can you think about a more specific description? Does "Cluster Detail" make sense to you in thinking about this page?
- "Document Detail" page seems to include content as well as functionality, which is a little confusing to me; if you think they are important to include, could you group them semantically? (e.g. there are several functions related to image display). I think it would also be more readable if related content was grouped (I don't understand why other scholars' pieces have title, author, and date listed separately). 
- On the "Document Detail" page, what is "rearrange images on a canvas" ? 

The nav section indicates you're thinking about including breadcrumbs — based on the current site architecture, I'm not sure that's warranted, the site doesn't seem hierarchical enough to need that. Do you have a sense, will there be other sections on the site? Or will there be pages nested under the document detail page? Right now it seems like all the information for a document is on that detail page.

On the bigger picture: do you have a sense of what else will be included in the site architecture and how the pieces you've indicated now might connect?

**Comment by gissoo** [comment]
> Note from @gissoo in Slack 11/25:
> 
> > I have added the doc detail to the site architecture https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza?node-id=75%3A0
> 
>     * "Document List" seems vague to me, can you think about a more specific description? Does "Cluster Detail" make sense to you in thinking about this page?
> 

Thank you for looking, super helpful!!
[Here is the revised sitemap](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza?node-id=75%3A0)
- thank you!! I have revised it. 

>     * "Document Detail" page seems to include content as well as functionality, which is a little confusing to me; if you think they are important to include, could you group them semantically? (e.g. there are several functions related to image display). I think it would also be more readable if related content was grouped (I don't understand why other scholars' pieces have title, author, and date listed separately).
> 

- thanks for catching that!! Does my revised version make more sense? I'm thinking of the image capabilities and transcription ones together/to me they are not really separate, let me know how you think about it. Also, the reason I put title, author, and date separately is because I'm thinking about them as separate fields, and that's what we also did for startwords sitemap. Please tell me more on why it's not making sense here. 

>     * On the "Document Detail" page, what is "rearrange images on a canvas" ?
> 

- I don't know what to call this feature yet :)) – did you look at it on the detail page design? [Here is my comment about it (last bullet point)](https://github.com/Princeton-CDH/geniza/issues/34#issuecomment-738404185)

> 
> The nav section indicates you're thinking about including breadcrumbs — based on the current site architecture, I'm not sure that's warranted, the site doesn't seem hierarchical enough to need that. Do you have a sense, will there be other sections on the site? Or will there be pages nested under the document detail page? Right now it seems like all the information for a document is on that detail page.
> 

- that's a great point! I have removed it for now. 

> On the bigger picture: do you have a sense of what else will be included in the site architecture and how the pieces you've indicated now might connect?

- I'm still working on this. It became heavier than I expected, will share more with you next week.

**Comment by rlskoeser** [comment]
@gissoo thanks for the revisions. "Cluster Detail" is a lot more meaningful to me as a label.

>  I'm thinking of the image capabilities and transcription ones together/to me they are not really separate, let me know how you think about it. Also, the reason I put title, author, and date separately is because I'm thinking about them as separate fields, and that's what we also did for startwords sitemap. Please tell me more on why it's not making sense here.

It was confusing to me on the startwords sitemap too — I think I remember some brief discussion of it there.  I may have let it go on that one since I wasn't the tech lead and it didn't seem to bother the tech lead!

It's confusing to me because there is such a long list of things and the list doesn't tell me how the relate. if you nested it the way you've updated the image functionality, I would find it a lot more readable / comprehensible.  So, maybe there's a heading of list of scholar pieces (why is "other" here?), with a sublist of all the related information you expect to see: title, author (=names?), date, type (?). That would probably make it easier to see when there's something I'm not sure about — like "location of other pieces/page numbers": now that I'm looking again more carefully, I see this one, and I'm not sure what it is. I don't remember noticing it before.

Looking again, the same kind of grouping would be really helpful on cluster details: some of the items you have listed apply to the entire page (tags, document count), but then the rest (I think?) apply to each individual result, and would be repeated. To me, those don't belong on the same level.  I think either a nested list or a nested box would help convey that better.

I'll look at the "rearrange images" feature and respond to it on the other issue. 

I get what you mean about image + transcriptions being connected; I don't feel strongly about this, but a couple of thoughts:
1. It is possible we will have transcription with no image. Also probably lots of cases where we will have image but no transcription! We'll need to make sure the interface & functionality works for all cases as well as it can with the data available.
2. By listing it as "image" instead of "image + transcription" it seems that you are privileging images over transcription; if they are connected, maybe list them together?

One last observation: the last section on the Document Detail, about what scholars' pieces included: I think the information architecture level doesn't need to say (and perhaps _shouldn't_) _how_ we will implement or convey something. Could this be described as an overview of available scholarship? I'm also not sure how we will get the information you're proposing; I think we have some of it now but I'm not sure we have all of it (but I'm not entirely sure what you mean by discussion or image).

**Comment by gissoo** [comment]
> @gissoo thanks for the revisions. "Cluster Detail" is a lot more meaningful to me as a label.
> 
> > I'm thinking of the image capabilities and transcription ones together/to me they are not really separate, let me know how you think about it. Also, the reason I put title, author, and date separately is because I'm thinking about them as separate fields, and that's what we also did for startwords sitemap. Please tell me more on why it's not making sense here.
> 
> It was confusing to me on the startwords sitemap too — I think I remember some brief discussion of it there. I may have let it go on that one since I wasn't the tech lead and it didn't seem to bother the tech lead!
> 
> It's confusing to me because there is such a long list of things and the list doesn't tell me how the relate. if you nested it the way you've updated the image functionality, I would find it a lot more readable / comprehensible. So, maybe there's a heading of list of scholar pieces (why is "other" here?), with a sublist of all the related information you expect to see: title, author (=names?), date, type (?). That would probably make it easier to see when there's something I'm not sure about — like "location of other pieces/page numbers": now that I'm looking again more carefully, I see this one, and I'm not sure what it is. I don't remember noticing it before.
> 

- thanks for pointing that out – I agree with how you're thinking of organizing them. That being said, sorry that I couldn't remember any discussion on it and thought we had all agreed after our conversation on sitemaps which was my only motivation for communicating it this way, so going forward let's agree on what matters to you when you're looking at a sitemap and siteflow map so that we can have one consistent structure for our sitemaps and siteflows, my goal has always been to keep these consistent so that we wouldn't talk as much about what the structure/organization is. 

> Looking again, the same kind of grouping would be really helpful on cluster details: some of the items you have listed apply to the entire page (tags, document count), but then the rest (I think?) apply to each individual result, and would be repeated. To me, those don't belong on the same level. I think either a nested list or a nested box would help convey that better.
> 

> I'll look at the "rearrange images" feature and respond to it on the other issue.
> 

> I get what you mean about image + transcriptions being connected; I don't feel strongly about this, but a couple of thoughts:
> 
>     1. It is possible we will have transcription with no image. Also probably lots of cases where we will have image but no transcription! We'll need to make sure the interface & functionality works for all cases as well as it can with the data available.
> 

- great! yes, will work on those too – I think my goal was to give you everything I know on this level so you could tell me if there are gaps with the database model. But I realize that showing the other variations is also important to find out about the gaps. (like if I think of it a certain way for variation A and a different way for variation B would the database allow that: this kind of a thought) – thanks for calling it out :) 

>     2. By listing it as "image" instead of "image + transcription" it seems that you are privileging images over transcription; if they are connected, maybe list them together?
> 

- @rlskoeser  ahh that's a great point!! thank you!! (I was listing them as "image" in the older versions of the designs, not in the fragments that I have shared with you most recently – in fact in the newer versions there is "transcription" label and no "image" label (face palm))


> One last observation: the last section on the Document Detail, about what scholars' pieces included: I think the information architecture level doesn't need to say (and perhaps _shouldn't_) _how_ we will implement or convey something. Could this be described as an overview of available scholarship? I'm also not sure how we will get the information you're proposing; I think we have some of it now but I'm not sure we have all of it (but I'm not entirely sure what you mean by discussion or image).
> 

- I'm not sure I understand this point, I'll follow up with you about this. 

I'll close this issue for now, as a lot more changes have been needed for the sitemap.
