### ISSUE TITLE
Revise the sitemap and site flow diagram so that the project team would know about the content that would exist on the site and the possible ways they are connected

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#48]
[Here is a revision to the sitemap](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza?node-id=75%3A0)

**Comment by gissoo** [comment]
Note: 
- I have made a number of proposals and have color coded what I understand is for the long-term – It would be great if we can talk through these at some point. Feel free to comment on the Figma doc as it might be easier to refer to the pieces there since there are too many of them. 
- I did try to revise the format based on RSK's comments, however this is not great and I'm not sure I totally understand RSK's vision for it. But the three of us need to meet so that we can make some decisions on one format for sitemaps. I would like them to be as consistent as possible, and not have to change the way it's represented in different projects.

**Comment by rlskoeser** [comment]
@gissoo thanks for this updated sitemap + site flow diagram.

- I like the color coding for designating things that are long-term or potentially out of scope. Super helpful.
- I think the revised format, with indentation for grouping items, is working better. (I'm wondering what you think is not great. Agree that we should have a consistent format across projects.) I wonder if part of the problem with the format is that you're trying to do too much in a single diagram? (information architecture, page content, functionality...) I looked at our terms & definitions document to see if we had anything to spell out the goals of a sitemap; should we revisit that & clarify? Maybe you and I are trying to do / get different things out of this.

I find it confusing and a little overwhelming to have so many different sitemap variations. It's not always obvious to me what has changed from one version to another. I would like you to be a more opinionated here and propose what you think is the _best_ option, and then identify any places you have questions or there are decisions still to be made. If there are places where there is possible variation or possible future content, maybe that could be noted somehow in the same diagram? (e.g. the scholarship for a fragment — could be on the same page or a separate one).

The "explore fragments" feature idea is very interesting and exciting, but as you've noted and we've discussed it's a long term / possibly out of scope feature. I don't think you should give it so much space in the sitemap you're proposing at this point! A single placeholder without a lot of detail would be useful at this level so we know where it might fit in if and when we build it. Brainstorming right now about the possibilities seems premature; we will know so much more about the project and the data when and if we get to design and implement it. (And even if you want to make the case that it isn't premature, it doesn't belong _here_ — it doesn't help me understand how you're proposing to structure the site.)

Why do you include a sitemap for the conventional search? Do you think that's something we still need to consider? 

I worry I still may not be giving you the feedback you need. Are you including all these variations because you have questions for me? 

I suggest you revise and consolidate into a single sitemap+site flow diagram that you think is the _best_ option that you'd like to see us pursue. You can still note any questions/open decisions, possible variations and future pages or features (but I think long-term pages/features should have less detail; you could move those ideas somewhere else).

**Comment by rlskoeser** [comment]
@gissoo reviewing your usability testing findings document reminded me about the data download feature — would you add this to the sitemap?

**Comment by gissoo** [comment]
> @gissoo thanks for this updated sitemap + site flow diagram.
> 
>     * I like the color coding for designating things that are long-term or potentially out of scope. Super helpful.
> 
>     * I think the revised format, with indentation for grouping items, is working better. (I'm wondering what you think is not great. Agree that we should have a consistent format across projects.) I wonder if part of the problem with the format is that you're trying to do too much in a single diagram? (information architecture, page content, functionality...) I looked at our terms & definitions document to see if we had anything to spell out the goals of a sitemap; should we revisit that & clarify? Maybe you and I are trying to do / get different things out of this.
> 

-  I have drafted definitions along with more proposal for future approach for sitemaps and site flow diagrams. I think the main reason I had combined them together is because when I first joined the CDH we both agreed that having a separate sitemap diagram may not be useful enough, but at the time we weren't working on one, so in context I understand that that is also problematic in a different way.
 
> 
> I find it confusing and a little overwhelming to have so many different sitemap variations. It's not always obvious to me what has changed from one version to another. I would like you to be a more opinionated here and propose what you think is the _best_ option, and then identify any places you have questions or there are decisions still to be made. If there are places where there is possible variation or possible future content, maybe that could be noted somehow in the same diagram? (e.g. the scholarship for a fragment — could be on the same page or a separate one).
> 

- I have some ideas to communicating sitemap variations in the future. I'm definitely more opinionated now :D thanks for the feedback.

> The "explore fragments" feature idea is very interesting and exciting, but as you've noted and we've discussed it's a long term / possibly out of scope feature. I don't think you should give it so much space in the sitemap you're proposing at this point! A single placeholder without a lot of detail would be useful at this level so we know where it might fit in if and when we build it. Brainstorming right now about the possibilities seems premature; we will know so much more about the project and the data when and if we get to design and implement it. (And even if you want to make the case that it isn't premature, it doesn't belong _here_ — it doesn't help me understand how you're proposing to structure the site.)
> 

- I'm definitely surprised that you didn't find it helpful, I anticipated that you would ask me where on the site it would be even if it's a premature idea. From my perspective my intention is to make sure I communicate where a new idea might fit on the site even if for the long-term, because if we agree on a certain structure now and then think about the new idea's location on the site later and if at that point you have a different view than I do about where on the site it would be then I would have wanted to know that in the beginning because I might have approached the hierarchies differently. but I think I'll address this when we converse again on my proposed solution to these problems. 
 
> Why do you include a sitemap for the conventional search? Do you think that's something we still need to consider?
> 

- I wasn't sure where we stand, regarding priorities, so wanted to make sure I offer that as well. Your priorities and the project team. 

> I worry I still may not be giving you the feedback you need. Are you including all these variations because you have questions for me?
> 

- my general approach is to start wide, so I look at all the possibilities so we see the range of them, I don't like the designers' approach who only show one version and say "this is it" ...but again I have a solution for this as well, it might further lengthen my process though.  


> I suggest you revise and consolidate into a single sitemap+site flow diagram that you think is the _best_ option that you'd like to see us pursue. You can still note any questions/open decisions, possible variations and future pages or features (but I think long-term pages/features should have less detail; you could move those ideas somewhere else).

- did part of what you have suggested here for the Geniza meeting on Jan 21.

**Comment by gissoo** [comment]
> @gissoo reviewing your usability testing findings document reminded me about the data download feature — would you add this to the sitemap?
>

– I had already included this on the sitemap in the "search results" as "export data" – but maybe we should talk more about whether that is not what you thought this is.

**Comment by rlskoeser** [comment]
Thanks, @gissoo — I think I didn't notice that until after I asked. I'm fine with including it there for now, and I'd prefer if we don't need a separate page for exporting data (as long as it doesn't unnecessarily complicate the search page).

**Comment by rlskoeser** [comment]
@gissoo regarding this comment:
> ... I anticipated that you would ask me where on the site it would be even if it's a premature idea. From my perspective my intention is to make sure I communicate where a new idea might fit on the site even if for the long-term ...

This got me thinking, had to figure out why I didn't feel like I needed to know much about this — I _think_ it's because the ideas you are proposing don't disrupt the site architecture for the core content and features we are planning to implement. They seem like they can be added later without changing the other parts of the site. It's helpful to know there might be _other_ things at that level at some point in the future, but beyond that I'm not sure how much detail I want. (This might be partly because they are exciting ideas and I don't want to get too distracted by them.)

Thank you as always for being so open and transparent and inclusive about your approach!
