### ISSUE TITLE
As a content editor, I want to see the number of documents we have in each language/script combination, so that I can understand the relative proportions and provide information for data visualization and research. 

### ISSUE THREAD

**Issue by sluescher** [Princeton-CDH/geniza#55]
## testing notes
on the language+script admin list view, confirm that:
- [x] counts are present and accurate for language
- [x] counts are present and accurate for probable language
- [x] clicking on language count takes you to the correctly filtered document list 
- [x] clicking on probable language count takes you to the correctly filtered list
- [x] sorting on language and probably language counts works

----

This is in the "language/script" interface.

**Comment by rlskoeser** [comment]
@richmanrachel @mrustow do you want document counts for probable languages as well?

**Comment by richmanrachel** [comment]
@rlskoeser - Yes, please!

**Comment by richmanrachel** [comment]
@rlskoeser - This blew our minds, we are so thankful!
- How did you populate the language and probable language fields??? This is amazing, but we don't quite understand how you pulled these documents. 
- Counts appear accurate for language and probable language (without double checking the metadata). 
- Filters all work.
- @gissoo: Can we please add filter by language on the front end? This is so cool and will be really useful for researchers who didn't know they could use the Geniza.
- Layout: In the "change document" interface, the language/probable language selection boxes are too large. If we could make them smaller, that would help overall page layout.
- Add help-text clarifying that these are languages spotted, not necessarily the language of the full document.

**Comment by rlskoeser** [comment]
@richmanrachel ah, good questions.

Testing of actual assignment of language and probable language imported from the spreadsheet is part of #66 . I think I documented in the testing notes how we're assigning them, but if that isn't clear please ask questions!

For sign off on this feature, please confirm that the filter is accurate by looking at a few of the documents returned and check that the language is associated.

Document edit interface is tracked in #68 — I will make a note on the language filters, I think we can switch to an autocomplete that should take up less room. Also, would be glad to add help text — please supply the help text you'd like for language and probable language as a comment on #68. (Keep in mind that help text is for content editors working in the backend system, we don't typically use the same language for the public interface.)

**Comment by mrustow** [comment]
Preamble: This would only apply to the "Languages + Scripts " interface, since in the "Documents" interface it will be clear from context. (I assume also in "Fragments" but it's down at the moment so I can't confirm.) Substance: When you hover over **# Documents** it would be helpful to see: "Number of documents on which this language appears," or some other wording to imply that this isn't necessarily the **only** language that appears. Actually I just realized, we can achieve the same effect by rephrasing the column header. So for "# documents," it would be good to see "# documents on which this language appears." For "# probable documents," it would be good to see "# documents on which this language might appear (requires confirmation)."

**Comment by rlskoeser** [comment]
@mrustow We prefer short labels for columns in django admin, because otherwise it makes the tables unwieldy.  I don't know of a built-in way to add help text for the columns.

Here's a screenshot showing the headings you requested:
![Screen Shot 2021-03-08 at 12 19 23 PM](https://user-images.githubusercontent.com/691231/110357067-e41afe00-8008-11eb-854f-766b3ea25443.png)

And here's a version when I force a line-break before the parenthetical comment:
![Screen Shot 2021-03-08 at 12 20 53 PM](https://user-images.githubusercontent.com/691231/110357084-e8dfb200-8008-11eb-88d0-e2605316834a.png)

There's also an option to add styles and set a maximum column width so the text will wrap as needed without me forcing a line break.

Do you still want me to proceed with this change?

**Comment by mrustow** [comment]
Here's the problem we were trying to solve. # documents, when your eyes are scanning down the list, implies (at least to me) that these are exclusive categories  so, 2k Arabic, 3k Hebrew, 6k JA, ok, that's 11k docs, nice. Except it's not--for all we know, it could be 6k docs total. When I rephrased the column header, this is what I was trying to fix. The other column was, if I recall, # probable documents? This was too compressed; it wasn't immediately clear to me what this implied. If having the text wrap wouldn't lead to unwieldy column headers, that seems to be a straightforward solution -- unless you can think of a briefer way to phrase them.

**Comment by rlskoeser** [comment]
@mrustow thanks for clarifying — that makes sense, especially in terms of the overlapping totals. I'm fine with that solution if you are! You will be using this system far more than I will. I just wanted to show you how it might look so you were clear what you'll be getting. 

If we think of a way to make them briefer it isn't hard to change the text, but nothing comes immediately to mind. I'll go ahead add the text wrapping.

**Comment by rlskoeser** [comment]
@mrustow @richmanrachel have revised the labels and set column max width, as discussed. Please confirm on the test site and close this issue if acceptable.

**Comment by richmanrachel** [comment]
@rlskoeser - Looks Great!
