### ISSUE TITLE
As a front-end user, I want to know which specific data are associated with each attribution, so that I am not confused by a list of attributions at the end of a transcription.

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#560]
## dev notes

- [x] cut the compilation/transcription language
- [x] display shelfmark & attribution for each fragment that has one

I think we need to figure out how to clarify what the Cambridge rights statement applies to (especially since we're not! displaying their metadata). Maybe display per shelfmark? Or group of shelfmark if they're the same, but sometimes there is small variation (IIRC some of the Cambridge attribution text had links but some did not; otherwise they were the same.)  

_Originally posted by @rlskoeser in https://github.com/Princeton-CDH/geniza/pull/546#discussion_r796041710_

**Comment by rlskoeser** [comment]
Looked at this with @richmanrachel on zoom and she said it looked good enough for now — she tuned it out as legalese, which means it isn't intrusive. :-) 

We may want to think about including rights statements on the how to cite or elsewhere once for each set of content, so that we don't have to display it on every page. But this is good for now.
