### ISSUE TITLE
Implement Turbo to improve internal link speed

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#635]
## dev notes

- [x] Use [Turbo](https://turbo.hotwired.dev/) convert all internal links to Turbo links.
- [x] Import Turbo in JS

**Comment by blms** [comment]
Running into some issues with Turbo.

When wrapping the "main" content block with a `data-frame`:
- Links to document detail pages in search results do not receive the correct CSS and do not change the window location/URL (I guess this is all within a single "navigation context")

When just enabling Turbo in `stimulus_app.js` and using no `data-frame`s:
- Seems to result in more FOUCs and slightly worse performance than before, at least when testing locally
- Search page seems to refresh twice on submit
- Filter modal will not open/close unless it is given `data-turbo="false"` attribute
- Cannot view more than one OpenSeadragon instance in the same navigation context, even if `data-turbo="false"` is set on a containing element

**Comment by rlskoeser** [comment]
@blms do you have a branch with your experiments that you could push so I can work with what you've already done?

**Comment by blms** [comment]
@rlskoeser here you go! https://github.com/Princeton-CDH/geniza/tree/feature/635-turbo

**Comment by rlskoeser** [comment]
@blms just pushed some changes to your branch:

- shift page-specific styles from `body` to `main` and update css 
- wrap `main` in `turbo-frame` so we get page-specific classname to trigger styling
- configure main turbo-frame with `target="_top"`; by default, links within a frame will stay within that frame, which is why loading the document page wasn't updating the url; I don't think we ever want that behavior, but I do wonder if we're losing some of the power/efficiency of turbo by doing it this way
- tweak openseadragon init to run on `turbo:load` event (proper solution will be to rewrite as a stimulus controller, but I think we have more changes we should incorporate and plan for in that change)
- placeholder styles for turbo progress bar (couldn't get our css variables to work)

take it for a spin and see what you think — any problems remaining? can we use this to turn on automatic form submission for search?

**Comment by blms** [comment]
Thanks so much @rlskoeser!

I'm still seeing a couple of problems, but I think there is enough for me to take it from here.

For documentation:

- Home and content pages are not picking up their CSS
- OpenSeadragon still not working intermittently, not sure what triggers a failure or a success, but I can start rewriting as a stimulus controller so as not to break things

**Comment by rlskoeser** [comment]
@blms I may have missed some of the css changes when I shifted things from body to main! I hope that's all it is.

I agree, switching openseadragon to a stimulus controller should resolve our problems — I thought about starting that and then figured out I shouldn't take it on. I think we should try to keep the new controller minimal for now — but if there's an easy way to switch to phosphor icons, that would be great (esp. since we don't have to load additional remote OSD icons)

**Comment by rlskoeser** [comment]
turbo is implemented and confirmed working in qa; testing and specific refinements will be tracked on #638
