### ISSUE TITLE
As a front-end user, I want the document search to automatically reload when I change my search terms, filters, or other options so tha I can see the changed results more quickly. 

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#638]
## testing notes (QA, round 2)

- [x] After making a search, navigate through the pages of results and click on a document. Hit the back button and confirm you remain on the page of results you were on before. Note any feedback about this overall interaction

---

## testing notes (QA)

- [x] On the document search page in the public site (QA), try entering some search terms, adding filters, and changing sort; confirm that the counts (for filters) and results (below search form) update automatically
- [x] Page through search results, click on some documents in the results, and note feedback here

---

related to #635

**Comment by richmanrachel** [comment]
@rlskoeser - overall it looks great and seems to be working well!

One little (probably) unrelated hiccup I'm noticing, is that if you click on an entry and then "back," you wind up on the first page of the results even if you were on another page. Is this expected behavior?

**Comment by rlskoeser** [comment]
No, it should go to the last page of results you were on — I noticed this too.

Let us know what else you find! We know there are still some things we need to address, but wanted to get some testing feedback on it.

**Comment by richmanrachel** [comment]
I still am missing a "reset filters" button, because manually unclicking is odd. 

I also worry that folks won't know to expand the document type filter. Perhaps scholarship records should be grouped together in the same way?

**Comment by gissoo** [comment]
@blms @rlskoeser this works well on all browsers: one Q: is it expected that you would have to click out of the search box to see updated results? results are not updated when I'm done typing till I click out of the search box – felt a bit weird. 

everything else is ok, tested on FF, GC, and Safari

@richmanrachel 
- the reset filters is on our list, just need to get to it!! 
- We've also discussed revising the way the scholarship records are positioned because stacking them won't probably be efficient – but I don't think we should "group" them as in they becoming selected by one click if that's what you mean? – (the results from earlier primary research showed that more people care about transcriptions but not necessarily translations, or they weren't looking for all three factors at the same time / in the same scenario.) 
- I think the doc type filter is clear but our revision of the position of the filters are probably going to help this as well – it's probably not efficient to spend more time on the UI for the filters till we have more filters to see what they would look like.

**Comment by richmanrachel** [comment]
@rlskoeser and @blms - it works! Oddly, when I didn't have any filters on, it navigated back to the correct page but not the same spot on the page. Whereas with filters, the back button got me exactly back to where I was. 

Should I close or do you want to improve the handling for the non-filter scenario?

**Comment by rlskoeser** [comment]
No time to fix if we still want to get a release out today; as discussed on Slack, we think this is good enough for now and will revisit as needed later.
