### ISSUE TITLE
As a content editor, I want to edit all of the documents associated with the fragment on the same screen that I use to edit the fragment, so that in the case of demerging I can make sure that the data is split correctly.

### ISSUE THREAD

**Issue by sluescher** [Princeton-CDH/geniza#65]
## Testing notes

- [x] On the fragment admin display, ensure that the fields are displayed properly in the TextBlock inline.
- [x] Click on the document string and ensure that it leads to the proper page.

---

## dev note
create simple inline for text block and enable on fragment edit
- editable: side & text+extent/region
- display document id + description

**Comment by richmanrachel** [comment]
I like where this story and functionality is headed, but maybe this is something I should work on with Nick this week. 

I really appreciate seeing the document descriptions within the fragment view, and the link to the document view page. 

What I'm not sure about is in a case like this:
![image](https://user-images.githubusercontent.com/68028846/116890790-004bad80-abfc-11eb-9918-1125ac48f4b9.png)

Only one side of this fragment should probably merit a PGP ID (because the verso is literary). But in a case where we discover that the fragment holds multiple documents, do we want the option to de-merge from this screen?

**Comment by richmanrachel** [comment]
Adding a text block doesn't allow me to split the description. I'm not sure it should, but just curious as to how this might leave us lacking?

**Comment by richmanrachel** [comment]
@rlskoeser - MR is very excited about this! One more thing that would be great is a way to link back to the fragment page from document view. Thanks!

**Comment by rlskoeser** [comment]
@richmanrachel I agree that it would be useful to easily get from document editing to fragment! Can we make a separate issue for that?

**Comment by richmanrachel** [comment]
@rlskoeser - Sure!
