### ISSUE TITLE
As a data editor, I want to search across multiple metadata fields so that I can find geniza items by keyword or phrase.

### ISSUE THREAD

**Issue by kmcelwee** [Princeton-CDH/geniza#7]
When searching by description, bring up sorted matches with their associated PGPID, library, and shelfmark. 

- [x] display tags on search result
- [x] display document type on search result
- [x] include library in fields searched

**Comment by kmcelwee** [comment]
Site is live! https://test-geniza.cdh.princeton.edu/

Testing notes:
- [ ] Can you successfully search on the most salient features of the metadata? (PGPID, description, library, shelfmark)
- [ ] To the best of your knowledge, is the metadata properly connected and formatted?

Also, we support more advanced search features that you're welcome to try. [Check out the documentation](https://prosody.princeton.edu/search/) from one of our other projects that shows some relevant functionality.

**Comment by sluescher** [comment]
I searched for the terms "Arabic" and "court" (see screenshot attached), and the first result does not include "court," but "Arabic" in the shelf mark. I would expect the first result to contain both terms.
Here the PGP link as well: [https://geniza.princeton.edu/pgpsearch/?a=object&id=30854](https://geniza.princeton.edu/pgpsearch/?a=object&id=30854 )
![Arabic court search](https://user-images.githubusercontent.com/30683720/96177308-aa334900-0efb-11eb-9d86-07ca7452c667.png)

**Comment by sluescher** [comment]
When searching for the library "Rylands," only results appear that either have "Rylands" in their description and/or shelf mark, but not those who have the value set as library (after | ).

**Comment by kmcelwee** [comment]
**Re: "Arabic court"**
https://test-geniza.cdh.princeton.edu/?keywords=Arabic+court
Although the Solr search algorithm uses relevance of the entire input to rank the output, it looks like the first result was weighted higher than the second because the word "Arabic" occurs in both the fragment and the tags.

**Re: "Reylands"**
https://test-geniza.cdh.princeton.edu/?keywords=Rylands
I was unable to reproduce your results, would you mind sending me a link?

Both of these issues seem like they can be solved with faceting, which will be included in the next enhancement. @thatbudakguy any further thoughts on this?

**Comment by rlskoeser** [comment]
I just checked the solr config, we're not currently searching on the library field. Indexed fields are: pgpid, type, shelfmark, tags, editors, translators

**Comment by rlskoeser** [comment]
@kmcelwee I think it would displaying the tags on the search results would help with testing — I hadn't registered the fact that they weren't displayed until you mentioned it.

**Comment by thatbudakguy** [comment]
> it looks like the first result was weighted higher than the second because the word "Arabic" occurs in both the fragment and the tags.

if this is the case (sounds right to me), it would be solved by boosting the description text higher than the shelfmark, which I think we don't need faceting to do.

**Comment by rlskoeser** [comment]
@sluescher I see in my notes that Marina had indicated Library should be searchable. Should I add that to the fields that are searched?

**Comment by sluescher** [comment]
A few comments:

It would be immensely helpful to be able to **see type and tags** (UPDATE: tags now visible). I cannot really make sense of the results without knowing what they are (at this point at least). The "arabic court" example is one. Another example is when I search for "letter" ([https://test-geniza.cdh.princeton.edu/?keywords=letter](https://test-geniza.cdh.princeton.edu/?keywords=letter)), the third result is the record with PGPID 16041 (ENA 1822a.33) which does not contain 'letter', but only 'Arabic script', though its type is letter. 

Related to that, the shelf mark I mentioned (ENA 1822a.33) has three (!) records in the PGP with different descriptions. The other two entries (PGP IDs 11066 and 6606) have 'letter' in the description and as a type, but don't show up in the search result above. The difference is that 16041 has 'private letter' as a tag, which seems to override the description in terms of priority?

When I search for ENA 1822a.33, I get back the three records, but also some more. What's the connection? Couldn't figure it out (only comment on shelf marks, otherwise works well).

In terms of type, when I search for 'legal', [https://test-geniza.cdh.princeton.edu/?keywords=legal](https://test-geniza.cdh.princeton.edu/?keywords=legal), the first results are all letters with legal queries (in description and tag). It would be great, if I could specify that with 'legal' I mean the type; otherwise I am not sure exactly how to formulate the query to make sure I only get back 'legal' types.

There is (at least) one person that has a Hebrew and an Arabic name. The Hebrew name is Natan ha-Kohen b. Mevorakh, the Arabic Wahb b. Baraka. Neither of the ways I've searched has brought back the one description in which both are mentioned as the top result (tried: Natan ha-Kohen b. Mevorakh AND Wahb b. Baraka, "Natan ha-Kohen b. Mevorakh" AND "Wahb b. Baraka"->no results). Nonetheless, searching for: "yusuf b." OR "yosef b." does return what I want. What am I doing wrong.

There is a document I know of that deals with taxes and a person called Halfon. When I search for "tax* AND Halfon," the first result contains 'tax', but no Halfon, which is however the name of an editor (that I can't see). The other two documents contain 'tax' and 'Halfon', which would be what I am looking for. Can we discuss whether when we do 'keyword' searches, we are mostly interested in the description? 

The same Halfon has multiple names in the database (yay!). Halfon b. Menashshe, Halfon b. Menashe, Halfon b. Menasheh. I tried doing a search for "Halfon b. M*", but that does not return anything. What am I doing wrong?

Last, Halfon is both written with and without diacritics. There is one record in which Halfon (with diacritics) and the Arabic name for colic (qawlanj) are mentioned in the description (PGP ID 30326), but when I search for "[Halfon AND qawlanj](https://test-geniza.cdh.princeton.edu/?keywords=Halfon+qawlanj)" it only appears as the sixth result? No colic in the first five.

**Comment by sluescher** [comment]
@rlskoeser yes, libraries would be nice too!

**Comment by rlskoeser** [comment]
I've updated the prototype to show document type (🤦‍♀️  can't believe we didn't include it from the outset — but good to learn how important it is for you when looking at results!).

Should the search results display all the fields that are searchable? It seems like it's hard to test what's going on when you can search on things you can't see. Currently that's editors & translators.

So, one thing to note is that we haven't done _any_ configuration on which fields are more important for searching than others. I'm not sure how much we want to invest in this right now because I'm not sure how much it will help us later since our data is going to change a lot — but we could try making some adjustments for basic things like description and tags that we know are going to stick around.  I think some of the results you're reporting (like **arabic script**) are likely due to the fact that Solr weights a match in a shorter field as more relevant than a match in a longer field.  I think we could also boost phrase matches higher.

Another thing to note is that by default the search matches any part of your search. If you search **ENA 1822a.33** without quotes, you should get the items with matching shelfmark first (since they are the most relevant), but other records with **ENA** or **1822a.33** will also be returned.  If you search **"ENA 1822a.33"** _with_ quotes you should only get results that match that phrase / shelfmark exactly.

> Can we discuss whether when we do 'keyword' searches, we are mostly interested in the description?
This is a _great_ question to be asking. Deciding which fields to include in a keyword search is important and not always easy! From the results you're getting, it seems like keyword search on tags isn't particularly helpful right now. I think keyword searches probably work best on test like descriptions and transcriptions (once we get them indexed).

I haven't implemented unicode folding yet — that's tracked in #9 — which might answer some of what's going on with the names you described.

**Comment by sluescher** [comment]
I think it would be helpful to have all the fields displayed. It'd be easier for me to understand the rationale behind the results?

Happy to wait on importance (or better, now that I will see type/tags/etc. it'll be easier for me to understand the search results).

Thank you!

**Comment by sluescher** [comment]
Hi again,

is the library now searchable? Searching for Rylands still only gives me 2 results, so I assume that isn't the case.

When I search [JRL](https://test-geniza.cdh.princeton.edu/?keywords=%22JRL%22) (which is the Rylands shelf mark), the first two results are not from Rylands, but have JRL in the description. When searching for shelf marks, I would want the result to first give me the documents with that shelf mark. Is that something that can be done?

Searching for multiple keywords works great! First time I was able to find all documents with "tax" AND "farming." 

Is it normal that I am not able to go past 20 records? For example, it will say 20 out of 24 records, but there's no way to get to the last 4?

**Comment by rlskoeser** [comment]
@sluescher I haven't had the chance to update to include library in the search fields yet, sorry.

Yes, we could prioritize matches on shelf marks. I'm not sure how much we want to work on prioritizing fields, inclined to put this as something we'll want to think about and refine down the road — but if it would be helpful we could take some initial steps towards boosting particular fields. If we do, that should be tracked in a separate user story.

Glad that multiple keywords is working well! I can't remember if I mentioned, you should also be able to use proximity  searching with this syntax **"tax farming"~5** to find words near each other. (Although the descriptions are probably short enough that everything is close together right now).

I never responded to one of your questions:
> The same Halfon has multiple names in the database (yay!). Halfon b. Menashshe, Halfon b. Menashe, Halfon b. Menasheh. I tried doing a search for "Halfon b. M*", but that does not return anything. What am I doing wrong?

I don't think you can use a wildcard inside an exact phrase.  We should keep this in mind as an example search to handle better in future! (I wonder if phonetic searching would be helpful).

Can we decide on what is needed for this first basic search story to be acceptable and signed off? My sense right now is:
- make it possible to search on library
- display editor and translator (since they are searchable)

How does that sound to you?

**Comment by rlskoeser** [comment]
Forgot to answer about pagination! Yes, we would normally have it. I wasn't sure how much it mattered for a prototype — is it important for testing? Could we just display more results to help you test, for now? (Although it might actually matter to see the _last_ results for a particular search, in some cases... but I'm inclined to keep this prototype as simple as possible and focus on things we haven't implemented before.)

**Comment by rlskoeser** [comment]
@sluescher have updated the prototype as follows:
- library is now searchable
- editor and translator are shown when present
- returning first 50 results instead of 20

Let me know if there's anything more you think needs to be done to call this first basic search story complete. (And let's figure out where to start documenting all the questions and ideas coming from testing!)

**Comment by sluescher** [comment]
> Yes, we could prioritize matches on shelf marks. I'm not sure how much we want to work on prioritizing fields, inclined to put this as something we'll want to think about and refine down the road — but if it would be helpful we could take some initial steps towards boosting particular fields. If we do, that should be tracked in a separate user story.

Agreed that it's something we want to think about. I am happy to talk about it at one of our meetings to also get Marina's input. 

> @sluescher I haven't had the chance to update to include library in the search fields yet, sorry.
> 
> Yes, we could prioritize matches on shelf marks. I'm not sure how much we want to work on prioritizing fields, inclined to put this as something we'll want to think about and refine down the road — but if it would be helpful we could take some initial steps towards boosting particular fields. If we do, that should be tracked in a separate user story.
> 
> Glad that multiple keywords is working well! I can't remember if I mentioned, you should also be able to use proximity searching with this syntax **"tax farming"~5** to find words near each other. (Although the descriptions are probably short enough that everything is close together right now).
> 
> I never responded to one of your questions:
> 
> > The same Halfon has multiple names in the database (yay!). Halfon b. Menashshe, Halfon b. Menashe, Halfon b. Menasheh. I tried doing a search for "Halfon b. M*", but that does not return anything. What am I doing wrong?
> 
> I don't think you can use a wildcard inside an exact phrase. We should keep this in mind as an example search to handle better in future! (I wonder if phonetic searching would be helpful).
> 
> Can we decide on what is needed for this first basic search story to be acceptable and signed off? My sense right now is:
> 
>     * make it possible to search on library
> 
>     * display editor and translator (since they are searchable)
> 
> 
> How does that sound to you?

Sounds good! And I see you already implemented all of it, so happy to sign off.

> Yes, we could prioritize matches on shelf marks. I'm not sure how much we want to work on prioritizing fields, inclined to put this as something we'll want to think about and refine down the road — but if it would be helpful we could take some initial steps towards boosting particular fields. If we do, that should be tracked in a separate user story.

Agreed that it's something we want to think about. I am happy to talk about it at one of our meetings to also get Marina's input. 

For the pagination, it was just something I noticed and thought I would bring up :D

> And let's figure out where to start documenting all the questions and ideas coming from testing!
Yes, let's. Should I create a "Search protocol"? Linking these threads and reflecting the main questions that arose?
