### ISSUE TITLE
Implement designs for the homepage banner for light and dark mode for desktop and mobile

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#750]
## testing notes (qa)

After a hard refresh, check the homepage banner on QA in:
- [x] Desktop, light mode (1440px)
- [x] Desktop, dark mode (1440px)
- [x] Mobile, light mode (320px)
- [x] Mobile, dark mode (320px)

And confirm they look as expected.

I made assumptions about how the banner should behave when at greater or less than the exact widths of 1440px and 320px. Please also:

- [x] resize your browser to different widths and leave any feedback about this behavior.

---

the assets had already been uploaded to github, however here is a link to [the designs on Figma](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza-(Project-team)?node-id=2714%3A11408) so you can see how they are all supposed to look together on desktop and mobile

**Comment by gissoo** [comment]
@blms Thank you!! This looks great! A big issue is I wonder if we made this complicated by how we decided to export its pieces. The green shape and the text are always supposed to overlap in one fixed position on any width – like how it's shown on the designs, like the below – that is really the whole point of the banner image otherwise it doesn't conceptually make sense – how can we make that happen without too many implications? Should we try to have it all in once piece? (I might have already exported it as one piece too) – let me know

<img width="811" alt="Screen Shot 2022-04-14 at 3 02 27 PM" src="https://user-images.githubusercontent.com/44615389/163458858-794ffabf-6e64-45eb-8fe3-75fd7790591d.png">

**Comment by blms** [comment]
@gissoo I was wondering if that should be the case! A question I had about that is how exactly that should work; i.e., should they all hang out in the center, or should they be anchored to the left as a group?

If they are all centered, then there is a problem that the left edge of the fragment becomes visible.

<img width="1779" alt="Screen Shot 2022-04-14 at 3 16 13 PM" src="https://user-images.githubusercontent.com/7234006/163461151-e281e1b2-79ca-4154-8367-32ea0677c824.png">
<img width="1788" alt="Screen Shot 2022-04-14 at 3 16 47 PM" src="https://user-images.githubusercontent.com/7234006/163461178-87e48490-2cd5-4532-a3d0-f21b714d5d67.png">

If they are anchored to the left, then there is a problem that the PGP text starts to drift from the rest of the page.

<img width="1792" alt="Screen Shot 2022-04-14 at 3 18 44 PM" src="https://user-images.githubusercontent.com/7234006/163461220-37b1c68a-b592-46d1-a7ad-55797167fecc.png">
<img width="1792" alt="Screen Shot 2022-04-14 at 3 19 09 PM" src="https://user-images.githubusercontent.com/7234006/163461226-4ff6c832-06bb-4250-aa58-489b50b9312c.png">

Which alignment is preferable? If the centered alignment is, can we change the fragment images so that their left edge is totally transparent?

**Comment by gissoo** [comment]
@blms thanks for the suggestion, super helpful! I have revised and uploaded the four fragment visuals in their folders on github – thanks!!

**Comment by gissoo** [comment]
@blms these look amazing!!! Thanks so much!! you're the beSTTT!! 
The only view that could improve is probably the tablet view but it's not what we are prioritizing and it really doesn't matter, it still looks fine.
