### ISSUE TITLE
As a content editor, I want to add and edit tags on a document via autocomplete, so that I can reuse existing tags when appropriate.

### ISSUE THREAD

**Issue by sluescher** [Princeton-CDH/geniza#76]
## testing notes
login and test as content editor:
- [x] testing typing a few words to find and add an existing tag to a document
- [x] test removing a tag
- [x] test adding a new tag to the document
- [x] test browsing the full list of tags

----
When adding new tags to documents, the options should be available in autocomplete.

**Comment by rlskoeser** [comment]
@sluescher should content editors be allowed to add new tags, or can they only choose from existing tags?

**Comment by sluescher** [comment]
at first I thought no. But. They will be doing most of the entries, so I think it would be helpful for them to have access.

**Comment by rlskoeser** [comment]
@sluescher  or @richmanrachel is this story about managing tags in general, or should we revise to make it specific to the desired autocomplete behavior for adding tags to documents?

**Comment by richmanrachel** [comment]
@rlskoeser - I don't think we envisioned creating a tag prior to it existing in connection to a document, so I think the latter?

**Comment by rlskoeser** [comment]
Switching from 1pt to 0 since this is trivial with taggit-selectize.

**Comment by richmanrachel** [comment]
Everything works great! I love the autocomplete, and adding and deleting tags is super easy.

Just to clarify about the browse tags view: "Slug name" is the unique identifier for tags that would otherwise be too similar? Hopefully as we integrate the cleaned up date from our recent data-thon, a lot of them will go away. @thatbudakguy - we can discuss this integration in our meeting this week, perhaps?

Would it be possible to make the Browse Tags more similar to the Language List View where we can see the number of related tags and click to see the documents tagged as such? (I'll close this issue and create a separate story after hearing back from you).
