### ISSUE TITLE
As a content editor, I want to be able to flag and annotate a fragment as needing examination by a global admin, so that the global admin can either resolve the issue or submit a request for changes to the CDH. 

### ISSUE THREAD

**Issue by sluescher** [Princeton-CDH/geniza#77]
Same idea as in #62 but for fragments.

## testing notes
- [x] edit a few fragments, add text to the 'needs review' field, and save
- [x] navigate to admin main index page: the fragments you edited should be listed as awaiting review
- [x] you should be able to click on the fragment to go straight to the edit page
- [x] you should be able to click on the fragment heading to go to a filtered fragment list view showing all fragments that need review
- [x] navigate to the corpus section of the admin site; confirm that the awaiting review section appears and functions the same as on the admin index page
- [x] create a test staff user account without permissions to view or edit fragments and login as that user to confirm that they do not see the list of fragments awaiting review

## dev notes
implementation is the same as #62

**Comment by thatbudakguy** [comment]
@mrustow and others - given discussion on #78; could we think more about this one? under what circumstances would a fragment need review (rather than a document)? consider that if several documents on a single document needed to be marked for review, you could:
- go to the document list in the admin
- filter/search to limit to documents with the shelfmark of the fragment in question
- proceed to mark each of the relevant documents as needing review

if you already have some workflows in place for reviewing whole fragments at a time, this issue isn't hard to implement, but want to make sure that there's a unique use case separate from #62.

**Comment by richmanrachel** [comment]
@thatbudakguy - I think because fragments are connected to shelfmarks and therefore to libraries, this type of flagging is still important so that a Content Editor can let the Admin know if a library has changed names, therefore making the shelfmark out of date. 

I agree with the discussions from #78 that we should icebox suppressing fragments, but I think flagging fragments as a whole is still useful.

**Comment by thatbudakguy** [comment]
makes sense; thanks for explaining! @kmcelwee let's keep the fragment-related work in #102.

**Comment by richmanrachel** [comment]
It's possible to add text to "Needs Review" and it shows up when done by Admin, but Content Editor flags are not showing up. Even for Content Editor, they only see Admin "needs review" and not their own.

Other things with checkmarks work.

But I'm confused by all the user permissions and don't know which groups/things to add to make the new staff detail work. Please help me, @rlskoeser or @thatbudakguy!

**Comment by rlskoeser** [comment]
One clarification — anyone who can see the 'needs review' list will see _any_ document that needs review, no matter who added the note. 

I'm not sure what you mean by "content editor flags".

**Comment by richmanrachel** [comment]
Update, thanks to RSK we were able to make Test Staff permission work!

**Comment by richmanrachel** [comment]
All good on all three of the outstanding issues. Woohoo!
