### ISSUE TITLE
As a content editor, I want to suppress fragments, so that the records are kept updated.

### ISSUE THREAD

**Issue by sluescher** [Princeton-CDH/geniza#78]
Same as #63 but for fragments.

## dev notes
should work similar to #63, with one addition: add validation to disallow suppressing a fragment with unsuppressed documents (i.e. fragment can only be suppressed if all associated documents are already suppressed)

**Comment by thatbudakguy** [comment]
@richmanrachel @mrustow should suppressing a fragment necessarily suppress all the documents on that fragment?

**Comment by mrustow** [comment]
Suppressing a fragment shouldn't necessarily suppress all the documents on that fragment. This I can say with 100% certainty.

**Comment by richmanrachel** [comment]
@thatbudakguy - I'm not sure I have the full context here. In what situation would we be suppressing fragments? I read through #63, but I still don't understand.

**Comment by mrustow** [comment]
I guess theoretically I could imagine a set of circumstances in which you'd want to preserve one part of a join and not the other. E.g., Bodl. MS Heb. b 18.23 + ENA 3974.3: On recto, they're a join. On verso, they're not. (Well actually they are, since a tiny triangle of the top document is stuck to the bottom document, but let's just pretend it's a clean break.) So if you wanted to know something about the doc's reuse, then you'd look at the verso, and that would lead you to the join. But suppressing all fragments in a join by suppressing one shouldn't be a default option.

**Comment by thatbudakguy** [comment]
> In what situation would we be suppressing fragments?
@rlskoeser and I were just wondering about this as well. what's the most common case for suppressing a document? would there ever be a situation where it's too difficult or insufficient to just suppress all the documents on a particular fragment?

**Comment by mrustow** [comment]
lol I think the most common circumstance would be when we have an entry that someone (say, um, me) threw in a few years ago as part of a massive batch of stuff flagged as documentary somewhere (like, um, say, FGP), and then someone actually responsible (like, say, um, Alan) came along in 2021 and realized it was literary. We're going to have hundreds of these, and there's an argument to be made for suppressing them so we don't water down the database, but not destroying them in case idk FGP dies or the Russians hack the NLI and we're the last ones standing.

**Comment by rlskoeser** [comment]
What if we add validation so you aren't allowed to suppress a fragment with unsuppressed documents?

**Comment by mrustow** [comment]
Exactly what I was thinking

**Comment by rlskoeser** [comment]
Great, I'll add that to the implementation instructions.

**Comment by thatbudakguy** [comment]
i think we might want to hold off on implementing this until we know more about how fragments will be represented. i still have some questions about how it would be used.

ontologically speaking, a fragment cannot be literary – only a document can be (fragments are just physical objects that host documents). in my mind, there is only one case where one would want to be able to suppress a fragment specifically...

consider the case @mrustow describes, where some documents in the PGP are in fact non-documentary and shouldn't be shown. then assume that there is at least once instance where an _entire_ fragment consists exclusively of non-documentary material, and also assume that the user can visit some kind of public page for that fragment. in this case, we have to suppress the entire fragment to prevent the user from visiting a page that doesn't contain any useful information. in all other cases, we'd just suppress any literary texts or other documents hosted on the fragment, not the fragment itself.

imo if even a single "real" document is hosted on a fragment, we shouldn't suppress the entire fragment. the reverse is also true: a fragment is only considered suppressed if all its documents are suppressed. this means we can make fragment suppression automatically take effect.

does this make sense???

**Comment by mrustow** [comment]
Ouch my head. Yes I agree completely with this. In my example, I assumed fragment1 hosts document1, fragment2 hosts document2, then scribe Yusuf Shmo in the 11th c comes along and glues them together to write a very long document on their versos, document3. Say documents 2 and 3 are literary. We suppress them. We're still left with document1. Let's hold onto this scenario for future discussion: we might not care about the join because we only care about doc1, or we might still want to know about the join, because dude, I mean, some scribe glued frag1 together with frag2 so s/he must have had access to both, which tell us something about their afterlives, so we'd then care about the join but not about frag2. 🤕 In which case I'd just put the info in the description as an "On verso..." I'll stop now. Have a nice weekend!

**Comment by richmanrachel** [comment]
In conversation with Marina on 8/18/21, we decided that this isn't worth pursuing at this time.
