### ISSUE TITLE
As a user, I would like to see historic and converted dates in document search results so that I can easily scan date information when it is known.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#780]
## testing notes
- [x] document date should display in search results the same way it does on document details
- [x] documents without date should not have document date in search result

Here's a search to find all documents on the test site with any value indexed for document date https://test-geniza.cdh.princeton.edu/en/documents/?q=document_date%3A%5B*+TO+*%5D&sort=relevance  
(you may have to toggle back and forth between admin and public to see how it's structured / how it's displaying)

The way I have it indexed right now you can also do some limited searching; e.g, here are all the documents where the date starts with "Jum": https://test-geniza.cdh.princeton.edu/en/documents/?q=document_date%3AJum*&sort=relevance

## dev notes
- [x] update `Document` index data to include full display date
- [x] add the new field to the solr queryset so they will be aliased and returned 
- [x] display the new field on the document search result when set

**Comment by richmanrachel** [comment]
@rlskoeser - Looks great! Going to review this and #847 with Marina now, but I think we'll be good!

**Comment by richmanrachel** [comment]
@rlskoeser - We love it! 

The only question that came up (and you can tell us if this is too persnickety), is that Document Date, Input Date, and PGPID are all given the same weight in the document list view:
<img width="899" alt="image" src="https://user-images.githubusercontent.com/68028846/168894437-d9e39614-fd87-4cab-9279-618916a3cd83.png">

Whereas, in the doc. detail view, Document Date is rightfully more prominent: 
<img width="558" alt="image" src="https://user-images.githubusercontent.com/68028846/168894593-09235c43-d2e6-4ba9-a65d-1b77d00a495e.png">

@gissoo - would it be possible to make the list view more consistent with the detail view? Renaming "Input Date" to "In PGP since" and perhaps making the input date and PGPID fields dark gray (rather than black)? This will help users distinguish which information is directly about the document rather than the database.

**Comment by rlskoeser** [comment]
I've wondered about the discrepancy between the input date as displayed on search and the revisions we made on the document details page!

I think that should probably be tracked as a separate issue, though.

**Comment by richmanrachel** [comment]
@rlskoeser - great. I'll make a separate issue

**Comment by rlskoeser** [comment]
Closing based on testing feedback, since we've created another issue to track the discrepancies between search result and document detail display.
