### ISSUE TITLE
As a front end user, I want results boosted that match the exact language of my search query.

### ISSUE THREAD

**Issue by richmanrachel** [Princeton-CDH/geniza#814]
**Is your feature request related to a problem? Please describe.**
Related to what RR found while testing #706. But this should be true for all languages/scripts (English, Hebrew, Arabic) that the most relevant result is in the same language as the search query. 

## testing notes

- [ ] search on an Arabic term that also has Judaeo-Arabic equivalent matches; records with Arabic matches should be listed before the Judaeo-Arabic when sorting results by relevance

**Comment by rlskoeser** [comment]
I've revised the arabic to judaeo-arabic search term logic so that the arabic form is boosted. Please try it out to confirm. 

(I'm not sure what I can do about the language-specific boosting more generally, Solr boosting is typically based on fields).

**Comment by richmanrachel** [comment]
@rlskoeser - this does seem to help! When I search various terms with الله (God), the first ~25 results are entirely Arabic, then it becomes a mix.

When I searched مولاى ("my lord") though, I didn't get an Arabic transcription until #8.  *كنيسة (church/synagogue) did boost the 2 Arabic results to the top. 

So this is probably good enough for now?

**Comment by kseniaryzhova** [comment]
We did further testing with the word  مولاى ("my lord") and we did not get an Arabic-script search result in the thumbnail until no.8 (Hebrew script equivalent appeared in no.6). However, we looked into no.1 result as a full page and it did have an Arabic script result matching our word in the description (but it had no image or transcription), but we could not see this in the thumbnail search results. 

Is the issue with this search result a separate issue? Because technically the search results are being boosted, it's just not showing up in the thumbnail search result preview.

**Comment by rlskoeser** [comment]
@kseniaryzhova I think you're right — this sounds like a separate issue to me, if it's matching on the description (resulting in the higher relevance ranking) but not showing the match in context. The description should show the search term in context if there's a match, so I'm not sure what's going on here — any ideas? It doesn't seem to be an exact match, since if I do a Ctrl-F search on the details page for the first result 1 it doesn't get highlighted and my browser doesn't think there's a match.

**Comment by richmanrachel** [comment]
@rlskoeser - I think it's an issue of dots. The word in the first description has dots underneath the final letter (مولاي) - this is a case where ي  and ى are basically the same letter linguistically but are different key strokes on the computer. So it's interesting that the algorithm knows it's relevant but isn't pulling the match for highlighting...

**Comment by rlskoeser** [comment]
Thanks @richmanrachel, I wondered if it was something like that. This is helpful. I can check and see what the differences are on the fields that are searchable vs. where I'm pulling the highlighting.

Would you create a separate issue to track that? I think it's a bug, and it's separate from what we were testing here (which based on your reports seems to be working properly).
