### ISSUE TITLE
Search for sources isn't working as expected in admin interface.  

### ISSUE THREAD

**Issue by mrustow** [Princeton-CDH/geniza#831]
While attempting to correlate some Goitein editions with the correct "volume" of unpublished transcriptions (e.g., changing "S. D. Goitein, Unpublished transcriptions" to "S. D. Goitein, Unpublished transcriptions. (ENA)," I noticed two issues:

1. It's not possible to search with the full string
2. The dropdown list isn't alphabetized. 

This works fine:
<img width="886" alt="Screen Shot 2022-05-02 at 4 43 51 PM" src="https://user-images.githubusercontent.com/73319225/166326575-3fadfd0c-6831-4c35-aaaf-6e17e87e8e7b.png">

This still works fine: 
<img width="1035" alt="Screen Shot 2022-05-02 at 4 43 28 PM" src="https://user-images.githubusercontent.com/73319225/166326579-f62ef3de-2a84-46a5-8ddd-da050af44de0.png">

Add the period and it no longer works: 
<img width="980" alt="Screen Shot 2022-05-02 at 4 43 19 PM" src="https://user-images.githubusercontent.com/73319225/166326584-b592571a-b549-472a-8b57-2188c13e2721.png">

Delete the period and add the desired "volume" name and it no longer works:
<img width="1124" alt="Screen Shot 2022-05-02 at 4 43 10 PM" src="https://user-images.githubusercontent.com/73319225/166326586-095e56d8-5413-4cf1-835e-cb219cb48036.png">

And it would be superb if these were alphabetized.
<img width="695" alt="Screen Shot 2022-05-02 at 4 43 00 PM" src="https://user-images.githubusercontent.com/73319225/166326588-10383a17-a05d-42b2-a708-ce39c5d98d52.png">

Thanks!

**Comment by rlskoeser** [comment]
Following up on this:
- The source volume field was not configured as searchable, which is an oversight which I've remedied in eebe2351
- The search is based on the _fields_ in the model that we configure to be searchable  (i.e., title, author first name, author last name, etc); it does not search on the string version that we compile out of those fields when we combine them for display. Can you explain why you're trying to search on the full string?
- default ordering for sources is title, then year; ordering is case-sensitive. I don't have it set to order by author by default because there's some extra overhead in determining the first author. We could override that ordering for the admin site if it would make big difference. What ordering would be ideal, and how important is it?

**Comment by richmanrachel** [comment]
@rlskoeser - I think we've been searching on the string because that's what we see in the other footnote boxes, so it's the most intuitive (as author appears first). 

What you've described is really helpful (and wow, yes, just poked around a bit and it works so much better!). I guess I'm wondering if we should just provide help text/training for how to use the search?

**Comment by rlskoeser** [comment]
@richmanrachel that approach makes more sense to me! It's always better for users to have a better understanding of how the systems work.   

I'm not sure if there's a place for me to add help text here, but LMK what you think would be best and I'll look.

**Comment by richmanrachel** [comment]
I'll add a tip in the PGP Database Instructions and add a note on Slack for now!

**Comment by rlskoeser** [comment]
Great. So can we relabel this to reflect the bug I fixed (search for source doesn't work if you include volume) and we can close?
