### ISSUE TITLE
As a frontend user, I would like to see converted dates displayed in a standard, readable format so that I can easily understand the calendar information.

### ISSUE THREAD

**Issue by richmanrachel** [Princeton-CDH/geniza#847]
**Is your feature request related to a problem? Please describe.**
Improvement on current date handling.

**Describe the solution you'd like**
Date month, year. Ex. 1 January, 1232 CE.

**Describe alternatives you've considered**
MR wants this British style. RR wants to see more examples of specific date conversions from the corpus (for while MR said that having day come first makes the most sense, I'm not sure it does if that's the fuzziest part of the date -- to me "January" is more important than "1," and the year is the most important overall)

**Additional context**
There may be some additional decisions that need to be made about more complicated dates. For example:
- Thursday, 20 Iyar 4758 or 4768 AM (24 May, 998 or 1008 CE)	[Should we use 24 or 24th? Should Thursday actually be included in the converted date, and if so, should it be left untranslated for the Hebrew date "yom rivi'i"?]

**Comment by mrustow** [comment]
I think we should follow CMS style, and CMS style for dates is:

1. For CE dates, either American usage (`November 11, 1968` — month first, and comma between day and year) or British usage (`11 November 1968` — day first, no comma) is fine. BUT
2. For other calendars, day first is standard, so `17 Barmūda 1465`, or `7 Jumādā I 648 AH`,  or `14 Adar II (4)768 AM`. The day must be first because some of the months have numerals following (Adar I/II, Jumāda I/II, Rabīʿ I/II).
3. When using both CE and other dates, for consistency, follow British usage.

**Comment by rlskoeser** [comment]
Django by default will localize the modern dates. I've overridden the formatting for `en` locale to display as Marina requested when we have a full-precision date (year-month-day), and am using "month year CE" or "year CE" only otherwise.  We may need to adjust that and customize the formatting for other locales.  (Should "CE" be marked for translation?)  It may be good for you to see how it's working now when you switch languages on the test site, but we can review/refine non-english versions later as needed.

Right now I'm displaying full precision dates for date ranges generated from months or years in other calendars, which may not be what you want. I thought it would be easiest for you to see and respond to an initial implementation.

**Comment by richmanrachel** [comment]
@rlskoeser - I like it a lot! I think @mrustow should take a look too.

**Comment by richmanrachel** [comment]
We both agree it's great! Closing :)
