### ISSUE TITLE
As a frontend user, I want to search by partial shelfmarks so I can more easily find documents by exact shelfmark or groups of shelfmarks.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#863]
## testing notes

shelfmark indexing is configured with bigrams, so any match two characters or more should match within the shelfmark now

- [x] try searching for shelfmarks by partial match as keyword search
- [x] try searching for shelfmark partial match with `shelfmark:##` syntax

## dev notes
- configure solr to apply ngram search filter to shelfmark; adapt from similar work on mep for searching on partial names

**Comment by kseniaryzhova** [comment]
@rlskoeser Do you have recommendations for how to test this? When we put in T-S or NS in the search results, it is different than production site but hard to tell what the difference is (test site had slighly more search results). When searching with shelfmark syntax, it worked for NS, but does not work for T-S, likely because of the spacing. The latter (T-S) also did not work when we added quotation marks shelfmark:"T-S 12" nor did it work with shelfmark:"T-S 12*".

**Comment by rlskoeser** [comment]
@kseniaryzhova this is useful feedback. It may help to see what's going on a bit better if you sort results by shelfmark so you can compare production and test?

What I expected was that two-letter or longer strings should now match within shelfmarks anywhere (some cases worked before but not all, depending on how you segment the shelfmark you're searching). It's possible that characters like the `-` in `T-S` don't get preserved before the bigram filter I'm applying, and I may need to adjust that for shelfmarks.

What would be most helpful to me in practical terms: can I get a few different examples of shelfmark searches that people want to do that aren't working (i.e. searches Alan can do in PGPv3 but not in v4) and what results they expect for that search.

**Comment by kseniaryzhova** [comment]
So Alan would like the search results to mirror the old PGP version (see screenshot) - the dropdown search suggestions are comprehensive and in numerical order. 
![image](https://user-images.githubusercontent.com/105385128/186499727-b5b25eb8-66af-4202-8861-7991d2091143.png)
Currently on the test site, the same search T-S 10, does not yield results in numerical order (see screenshot below)
![image](https://user-images.githubusercontent.com/105385128/186500078-b36cd2ee-5562-4658-ac2d-5f337e406749.png)
Sorting by Shelfmark instead of Relevance is even worse, as we get a lot of AIU matches which mention T-S 10 documents (see screenshot below).
![image](https://user-images.githubusercontent.com/105385128/186500240-1ea1ef2b-7d3f-4841-9309-847b8a352466.png)

**Comment by richmanrachel** [comment]
@rlskoeser - I agree that searches like shelfmark:"T-S 10" should produce results. One use-case for this is to have the closest approximation of flipping through library binders of documents. I've been told some collections were good at curating like with like, but I've never had the experience of being able to see what characterized T-S 13 J versus T-S AS. 

The test site results for shelfmark:"13 j" are currently zero as well:
<img width="954" alt="image" src="https://user-images.githubusercontent.com/68028846/186744664-51de6ece-a502-4162-a329-b1d1ca056fff.png">
Without quotation marks, it's 307 results, but the "most relevant" is an ENA doc with neither number nor letter in the shelfmark:
<img width="652" alt="image" src="https://user-images.githubusercontent.com/68028846/186744926-695ffc92-f1de-44d1-acfd-313f7137765c.png">

**Comment by richmanrachel** [comment]
Perhaps part of the issue is the way relevance is being calculated? For example, the way that Goitein's generation cited a document was Bodl. MS Heb. b 12 (Cat. 2875), f. 2 Doc. 1. Today we ignore the catalogue number and write it as Bodl. MS Heb. b 12/2.

If I search the entire old shelfmark, I do get the proper document first (PGPID 6352). But if I knew just enough to know the old shelfmark looked wrong, but not enough about how to format it, I might search Bodl. MS Heb. b 12. This does eventually get me there, but the results feel chaotic by not having any numerical order:
<img width="618" alt="image" src="https://user-images.githubusercontent.com/68028846/186747055-ffd397f4-edad-40d1-99e4-05cdca5be28a.png">

**Comment by kseniaryzhova** [comment]
@richmanrachel could you weigh in? I am getting expected search results, more so with relevance than with shelfmark (for shelfmark, since it's in alphabetical order, I get joins which include one of my partial matches)

**Comment by richmanrachel** [comment]
@rlskoeser - the first problem I'm running into is that it's allowing me to have a search term while still sorting by random (which I know is not the correct logic we implemented....)

Searching for T-S NS J401 with relevance worked. The only oddity is that joins are being considered first, so the order looks odd: 
1. Legal documentT-S NS J401m + T-S NS J401k
2. Legal documentT-S NS J401l
3. Legal documentT-S NS J401a 
4. [then going 401b in alphabetical order]

The results are nearly identical when I add the shelfmark: syntax

**Comment by rlskoeser** [comment]
What I recommend is that we implement natural sorting for shelfmarks in Solr. I know how it needs to be done but didn't want to do too many changes at once, and I wasn't sure how essential this is. If you want to create an issue, I can add notes to the documentation / example config that I found (or maybe even add it quickly in next week!)

**Comment by rlskoeser** [comment]
@richmanrachel would you see if you can duplicate the random sort problem? Under what circumstances does it show up? I tested a little bit and it seemed like it was working ok, but I didn't test it for very long. If you can duplicate it, then yes, please open an issue and document when it's happening.

**Comment by richmanrachel** [comment]
@rlskoeser - it's working correctly for me now too!
