### ISSUE TITLE
Design the interactive experiences that can exist between the image and transcription/translation based on their relation so users can correspond to either side when using the transcription panel

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#866]

**Comment by gissoo** [comment]
@rlskoeser [Please take a look at the design proposals here ](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=1863%3A54363)– there are some for UI styles and some for interaction styles with detailed notes on the sides. Please let me know what you think about the proposals and feel free to omit some. We can talk in person about these as well today if you have time.

**Comment by rlskoeser** [comment]
@gissoo thanks for these proposals. 

I like proposal 1 for general approach: I feel pretty strongly that we don't want any outlines or indicators drawn on the image by default, and I think from conversations with the team that they would agree. 

For UI styles:
- I like the highlighting on the image better than an outline
- I like the green outline on the transcription text better than the other options, but I'm not sure how much I trust my judgement... I think the green border is not enough to see on the other side which line of text is active; I don't like the other text being so faded out... Maybe a green underline would be sufficient, instead of a box. Also that's likely easier/simpler if we're in a view where the transcription text wraps.

Did you consider dimming the rest of the image as a way to highlight the selected portion?

I see the problems on mobile... How important do you think it is to have this functionality on mobile? Maybe it needs a different solution that we could implement in a later round.

Question for you: when I initially migrate TEI content over, it will be attached to the whole image and not zoned to a particular block. I think that these kind of full-image zones should not have the interactions that you're designing here. Do you agree?
