### ISSUE TITLE
As a content editor, I want structured date information extracted from descriptions so it can be used for display, filtering, and sorting.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#874]

**Comment by richmanrachel** [comment]
@blms and @kseniaryzhova - is this user story worth keeping or has it been superseded?

**Comment by kseniaryzhova** [comment]
@blms @richmanrachel I think so, since now we can just generate our own csvs. I'll tag it as won't fix.

**Comment by blms** [comment]
@kseniaryzhova @richmanrachel  I'm wondering if this was partially solved by #1262, at least for inferred dates, since we did generate a CSV of those. Though, maybe the original goal of this user story was some kind of automated ingest as well? But given the inconsistencies in how the inferred dates were formatted in descriptions, my guess would be it would require a lot of cleanup before that, maybe to the point that it wouldn't be worth it. If this is definitely a `wontfix`, we can close!
