### ISSUE TITLE
As a content editor, I want to add and edit transcriptions on a separate page from the document detail or admin edit form, so that permissions and saving just the transcription can be managed more easily.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#911]
## testing notes (qa)

On the QA site (public site), ensure you are logged in. Visit a document details page for a document with one or more images and:
- [x] Confirm there is an "add or edit transcription" button on the page, above the images/transcriptions section
- [x] Click that button and confirm you are taken to a new page to edit the transcription
- [x] Confirm that all the functionality from https://github.com/Princeton-CDH/geniza/issues/757 is working the same way
- [x] Annotate on multiple pages of the same document
- [x] confirm you can access the transcription page from admin site when editing a document
- [x] confirm that when you are not logged in you don't see the add/edit transcription link on document details page
- [x] Confirm line numbers persist when you save them in the editor
- [x] Confirm ENA images load correctly (and open a separate issue if not)

## dev notes
- [x] new view and url for transcription editor
- [x] restrict to users with permission to change documents
- [x] link from document details and admin change form (probably in image+transcription viewer)
- transcription panel changes for editor integration:
  - [x] transcription panel should not be disabled even if no existing transcription
  - [x] deep zoom enabled by default
  - ~~disable toggles to turn off image/transcription if it causes problems (?)~~
- [x] apply transcription styles to editor transcription text (rtl, right aligned, etc)
- [x] update tahqiq instantiation as needed to attach to image and corresponding transcription panel
- [x] instantiate multiple annotorious/tahqiq instances, one per image

**Comment by richmanrachel** [comment]
@rlskoeser - testing round 2 and some things are working, but not all things...
1. Images from CUDL are working and I could add a transcription, but while it "saved" on the separate page, it didn't create an extra transcription on the front or backend (i.e. no footnote was created, so I couldn't toggle between my transcription and Goitein's) - is this current expected behavior? [I was testing on PGPID 1111]
2. For ENA images, it took a few reloads of the page for the images to show up.
3. I love how easy it is to add line numbers! But they didn't show up after I hit "save"
<img width="986" alt="image" src="https://user-images.githubusercontent.com/68028846/180800166-5545a8ec-f701-4574-a1d6-575e93cddfab.png">
<img width="929" alt="image" src="https://user-images.githubusercontent.com/68028846/180800217-477d1030-fce8-4d26-afb5-5dd0bd573138.png">

**Comment by rlskoeser** [comment]
@richmanrachel the transcription display on the frontend isn't based on the new data and transcriptions aren't linked to footnotes yet, so this is behaving as I expect it to for the current status — although I see now that it would be pretty useful for testing to be able to toggle between transcription view and public view, so perhaps I should probably prioritize that!

I think there's a style issue with the line numbering, we should fix that before considering this closed.

I'll see if we can reproduce the image loading problem.

**Comment by richmanrachel** [comment]
Success!
