### ISSUE TITLE
As a content editor I want to use basic formatting in transcription content so that I can enter lines as numbered lists or tag when the language changes within a document.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#916]
## Testing notes (qa)

After testing https://github.com/Princeton-CDH/geniza/issues/911, confirm that when you start editing an annotation body, you can use:
- [x] line breaks
- [x] numbered lists
- [x] language tags
- [x] strikethroughs

Also confirm
- [x] you can save formatted changes 
- [x] saved content with formatting displays when you reload the page

## dev notes
integrate tinymce editor into tahqiq text editing block

revisions after testing:
- [x] style superscript/subscript
- [x] style lists
- [x] allow deleting empty content annotations

glitch prototype: 
- code https://glitch.com/edit/#!/pgp-transcription-prototype?path=editor.html%3A1%3A0
- view https://pgp-transcription-prototype.glitch.me/editor.html

**Comment by richmanrachel** [comment]
This mostly works perfectly! The only feature that works in the edit field but doesn't save as such is the superscript.

The language tags stayed with the highlighted text even when I had two languages in the same transcription zone :) 

@rlskoeser and @blms - should I close because the testing features above worked, or mark as tested needs attention since there's still one available feature that doesn't save properly?

**Comment by rlskoeser** [comment]
@richmanrachel I suspect we are missing styles for that tag (similar to the list), so we should kick it back and fix that before closing.

Can you elaborate what you meant about the language tags staying with the highlighted text?

**Comment by richmanrachel** [comment]
@rlskoeser - great, thanks!

I meant that when I closed a transcription and re-opened it, that I could click the text and the language feature was highlighted and maintained the difference between the Hebrew and Arabic text blocks (this screen shot isn't great, but you can see that the language switcher is darker than normal because it's been activated)
<img width="512" alt="image" src="https://user-images.githubusercontent.com/68028846/180870458-0e049d11-6ece-4a0a-ad3b-3dcd1b9329f7.png">

**Comment by rlskoeser** [comment]
@richmanrachel thanks for explaining — that's great to hear, and a good confirmation that it's working as hoped.

**Comment by richmanrachel** [comment]
It works! Just want to bring to @gissoo's attention that the strikethrough lines through this Arabic font make the original word hard to read (sorry for the gibberish!)
<img width="510" alt="image" src="https://user-images.githubusercontent.com/68028846/182674883-08e6c420-21ac-43fe-a9a0-0ce72fbfc42b.png">
