### ISSUE TITLE
Design a control for image zoom so that users can zoom in on images on desktop 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#923]
- slider 
- this slider only exists on desktop
- the expected type of interaction is hold and drag and the expected behavior is the indicator would move right and left depending on the direction toward which it's dragged, which is also when the zoom % on the right would change.
- there is no "zooming out" of images, there is only going back to the default view. 

For accessibility: 
- the indicator would be tabbable and then the user would be able to use the left and right arrows to use the zoom functionality.

**Comment by gissoo** [comment]
@rlskoeser [Here are the designs I'm proposing for the image zoom slider](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=1784%3A43871) – I'm working on this in tandem with the toggle so that they look different enough from one another.  – please read the notes above.

I'm gravitating towards the circle. I've played with colors and these seem to be the most accessible. Please take a look at the dark mode as well. Let me know if you have any thoughts and suggestions. 

![Screen Shot 2022-06-13 at 5.20.47 PM.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/db7dd054-3e35-4de7-8fc2-c8481159a4bf)

**Comment by rlskoeser** [comment]
@gissoo replying while I'm thinking about it (instead of writing myself a note so I remember my thoughts to reply later... 🙄)

This is the direction I kind of thought you were going, and I like it a lot. I agree with you, I like the circle better than the other options.  Is there a semantic reason to color the range on the left of the slider? 

I have some implementation concerns, which I'll share, and you may have thoughts on — but I am inclined to start implementing this version (functionality + styles for position/size) so that we can see how these play out with a working prototype. 

My concerns:
- Will users know how left and right map to zooming in and out? Not sure if it's obvious. How do you feel about adding indicators to the ends of the slider?
- Based on the zoom slider example Ben shared, I wonder if this is too small a range for the slider; it might be fiddly to use, but I'm ok with trying it out at this size and seeing if we need to adjust.
- I'm not sure how openseadragon zoom levels are going to map to the % indicator you have here, or what the logic should be. Is 100% fully zoomed in as far as possible? Or is 100% the default size, and we zoom in and out from that? I propose that for the initial implementation we use openseadragon's built-in numeric zoom levels at first to see what we get.

This is my understanding of how zoom interaction should work, please correct or confirm: 
1. By default, image is static and not zoomable but the slider is displayed. 
2. Interacting with the slider should enable deep zoom and adjust the zoom level based on the change made in the slider input. 
3. Image continues to be zoom-enabled until zoom is disabled.

How does the user exit out of deep zoom? Does it happen automatically when they go back to the default zoom level? Is there any other way to turn it off?

**Comment by blms** [comment]
@gissoo I also don't seem to be able to style the "progress" or "lower area" of the slider, i.e. the green on the left side of the handle, in Chrome/Safari/WebKit. It's only style-able in [Firefox and Edge/IE](https://developer.mozilla.org/en-US/docs/Web/CSS/::-moz-range-progress) (and I noticed that Safari doesn't even have different colors for this on their [native slider UI](https://cloud.netlifyusercontent.com/assets/344dbf88-fdf9-42bb-adb4-46f01eedd629/dd5cbf69-d2c2-4412-93b1-a14b1eee6b9f/4-create-custom-range-input.png)). Should I go ahead and implement for Firefox and Edge/IE only, or should we style the slider track in a single solid color? If we choose the latter, should it be the gray color or should it be the green/pink?

**Comment by gissoo** [comment]
> @gissoo replying while I'm thinking about it (instead of writing myself a note so I remember my thoughts to reply later... 🙄)
> 
> This is the direction I kind of thought you were going, and I like it a lot. I agree with you, I like the circle better than the other options. Is there a semantic reason to color the range on the left of the slider?
> 

- @rlskoeser I'm glad!! :) 
- regarding the semantic reason behind the range color: this is the equivalent to the "Active" mode. This is an extremely common pattern for zoom sliders and it's almost confusing to not have it – it acts as a way to help the user learn the orientation and the direction of the control as well as the relationship between the numbers and the slider better. 
Your question triggered some thoughts: what about if we do [this](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=1808%3A46184)? – I think what I was proposing would have conflicted a bit with the "inactive" mode – so now once you drag towards the right the line wouldn't be grey anymore. 

> I have some implementation concerns, which I'll share, and you may have thoughts on — but I am inclined to start implementing this version (functionality + styles for position/size) so that we can see how these play out with a working prototype.
> 
> My concerns:
> 
>     * Will users know how left and right map to zooming in and out? Not sure if it's obvious. How do you feel about adding indicators to the ends of the slider?
> 

- I think this is pretty common would rather not have the indicators and test without them, but it's also fine to add the "-" and a "+" at the ends. 

>     * Based on the zoom slider example Ben shared, I wonder if this is too small a range for the slider; it might be fiddly to use, but I'm ok with trying it out at this size and seeing if we need to adjust.
> 

- I wondered about that too – my concern is the space – we need spacing for the rotation control as well so I'll need to think about a different way of organizing these if we want to make this larger. 

>     * I'm not sure how openseadragon zoom levels are going to map to the % indicator you have here, or what the logic should be. Is 100% fully zoomed in as far as possible? Or is 100% the default size, and we zoom in and out from that? I propose that for the initial implementation we use openseadragon's built-in numeric zoom levels at first to see what we get.
> 

- I'd thought it would make more sense for the default view to be 100%. 
> 
> This is my understanding of how zoom interaction should work, please correct or confirm:
> 
>     1. By default, image is static and not zoomable but the slider is displayed.
> 
>     2. Interacting with the slider should enable deep zoom and adjust the zoom level based on the change made in the slider input.
> 
>     3. Image continues to be zoom-enabled until zoom is disabled.
> 
>

- everything is correct! 

> How does the user exit out of deep zoom? Does it happen automatically when they go back to the default zoom level? Is there any other way to turn it off?
>

- I'd rather we don't add any toggles or buttons to turn off zoom – that's a lot of effort that's very uncommon and can get confusing, and it can also get very tiring – (won't be as tiring if we can turn it on and off for _all_ images on the page) – Also, your comments are giving me thoughts: the reason for "disabling zoom" will not be clear to users and it's unlikely they would know to go back to default view in my proposal or click a button to resolve the scroll trap – can we draw an outline around the "scroll trap" section of the image? (I can chat on Slack to explain more, but just wondering if this is possible)

**Comment by gissoo** [comment]
> @gissoo I don't seem to be able to style the "progress" or "lower area" of the slider, i.e. the green/pink on the left side of the handle, in Chrome/Safari/WebKit. It's only style-able in [Firefox and Edge/IE](https://developer.mozilla.org/en-US/docs/Web/CSS/::-moz-range-progress) (and I noticed that Safari doesn't even have different colors for this on their [native slider UI](https://cloud.netlifyusercontent.com/assets/344dbf88-fdf9-42bb-adb4-46f01eedd629/dd5cbf69-d2c2-4412-93b1-a14b1eee6b9f/4-create-custom-range-input.png)). Should I go ahead and implement for Firefox and Edge/IE only, or should we style the slider track in a single solid color? If we choose the latter, should it be the gray color or should it be the green/pink?
>

- @blms I'm not sure, definitely not the latter for the long-term, maybe it's fine for now till we find a solution.
