### ISSUE TITLE
I tried making changes in the admin interface > sources on my phone and they weren't saving:

### ISSUE THREAD

**Issue by mrustow** [Princeton-CDH/geniza#994]
![image](https://user-images.githubusercontent.com/73319225/181604405-711ca17b-69db-43e1-a433-e4e1c291ad47.png)

One ref read "no." instead of "doc."

![image](https://user-images.githubusercontent.com/73319225/181604449-ad3a698e-7800-483b-8ff6-9ba061560488.png)

![image](https://user-images.githubusercontent.com/73319225/181604463-49f11ce3-7a65-4c6e-a7b7-de5abec188fb.png)

Changed it, but when I hit save ... 
![image](https://user-images.githubusercontent.com/73319225/181604483-f883afe8-2875-42b5-9395-e25ab28c3448.png)

![image](https://user-images.githubusercontent.com/73319225/181604513-9bf82bac-1f30-4a38-84b6-421694901daa.png)

It just went back to the way it had been before. 

![image](https://user-images.githubusercontent.com/73319225/181604529-05a085ce-9ea5-471a-9ba5-8b901d6670fd.png)

**Comment by rlskoeser** [comment]
I think this is likely the same problem as #905, where sources with a lot of footnotes don't save because we're exceeding the number of allowed form submission elements.  I increased our config to 2000 (django default is 1000), and could try increasing that, but we probably need a better solution.

However, if you're trying to update footnotes we do have a good workaround — each footnote should now have a change link at the top of the row where it's listed, which will take you to the edit page for just that footnote.

**Comment by mrustow** [comment]
Ah nice, I hadn't noticed that change button, that's great. But for some reason when I went back to the same screen, the change button appeared on every row except the one in question. 🤔 ![image](https://user-images.githubusercontent.com/73319225/181611959-002edba0-31e0-4eef-ad50-1760817a5604.jpeg)

**Comment by rlskoeser** [comment]
@mrustow weird that the edit link is not showing! Could it be because the label for that footnote is longer? If you scroll horizontally on the page does it show?

**Comment by mrustow** [comment]
It didn't, but then I checked on desktop and it was fine ... who knows? Anyway, closing this as it's covered by #905.
